### ISSUE TITLE
`stream::Config` `duplicate_window` should be a `Duration`

### ISSUE THREAD

**Issue by paolobarbolini** [nats-io/nats.rs#1001]
### Use case

Use a better type for declaring the `duplicate_window`

### Proposed change

Make `duplicate_window` into a `Duration`
https://github.com/nats-io/nats.rs/blob/76789dfd3db62636929c254b9db550a5d488ae1e/async-nats/src/jetstream/stream.rs#L1026

### Who benefits from the change(s)?

Users of the library

### Alternative Approaches

Leave it as is but document the unit of measure

**Comment by Jarema** [comment]
Thanks @paolobarbolini! Good catch :).
