### ISSUE TITLE
Lazy/OnceCell crashes client on tokio runtime

### ISSUE THREAD

**Issue by NorbertBodziony** [nats-io/nats.rs#1025]
### NATS version

0.29.0

### rustc version

1.70.0

### OS/Container environment

MacOs Ventura 13.2.1

### Steps or code to reproduce the issue

Running into https://github.com/nats-io/nats.rs/issues/134 issue.

We hold below object inside OnceCell from tokio
```
pub struct Odin {
  pub client: Client,
  pub js_client: Context,
}
pub async fn get_odin() -> &'static Odin {
  static INSTANCE: OnceCell<Odin> = OnceCell::const_new();

  INSTANCE.get_or_init(connect_to_odin).await
}
```
We run our tests using command`cargo test -- --test-threads=1`. Test always crashes on `client.publish` with error 
`"failed to publish message: channel closed"` Pretty confident its issue with how Nats client interacts with OnceCell but cant figure out solution. Adding `flush` does not help. 

### Expected result

Nats should work inside OnceCell.

### Actual result

Crashes with error`failed to publish message: channel closed`.

**Comment by caspervonb** [comment]
Are you sure the server isn't shutting down on you?
Once initialized a client (or context, which holds a cloned client) shouldn't hang up unless dropped.

**Comment by NorbertBodziony** [comment]
So found more context to it. https://github.com/tokio-rs/tokio/issues/5064 Its actually issue with tokio and tokio test.
Feel free to close this issue.
