### ISSUE TITLE
Alphanumeric enforcement on `HeaderName` breaks Implementation with Memphis.

### ISSUE THREAD

**Issue by turulix** [nats-io/nats.rs#1030]
As stated above the Alphanumeric enforcement introduced in 0.30.0 breaks custom headers used by memphis.
https://github.com/nats-io/nats.rs/blob/cb0e15a7bad7a910266628662c1a477e46c7c106/async-nats/src/header.rs#L502-L504

Memphis uses Nats in the background and uses SpecialHeaders like `$memphis_producedBy` which inclue `$`, `_` and therefor triggering the `ParseHeaderNameError`

It also appears that the enforcement dosn't happen while inserting into the HeaderMap but rather when reading it at https://github.com/nats-io/nats.rs/blob/cb0e15a7bad7a910266628662c1a477e46c7c106/async-nats/src/connection.rs#L295
Causing the entire library to panic rather than returning an error.

But I don't understand why the headers are being restricted in the first place, as something like the headers above work absolutly fine, and I didn't find anything in the NATS documentation restricting the use of headers like that. I think if a user wants to use funky HeaderNames just let them do it.

**Comment by caspervonb** [comment]
> But I don't understand why the headers are being restricted in the first place, as something like the headers above work absolutly fine, and I didn't find anything in the NATS documentation restricting the use of headers like that. I think if a user wants to use funky HeaderNames just let them do it.

Header names are specced to be ASCII 33 to 126, excluding colon so that's why.
