### ISSUE TITLE
mTLS / add_root_certificate clarification

### ISSUE THREAD

**Issue by andrewbanchich** [nats-io/nats.rs#104]
I'm configuring NATS to [use mTLS](https://docs.nats.io/nats-server/configuration/securing_nats/auth_intro/tls_mutual_auth), and using [`add_root_certificate`](https://docs.rs/nats/0.8.0/nats/struct.Options.html#method.add_root_certificate) to pass in the `ca.pem` file that is just the public key of the CA.

The docs for `add_root_certificate` don't go into detail on what should be included in this file, and I don't see any equivalent to add client certs like the [Go client has](https://github.com/nats-io/nats.go#tls). I would have thought it would just be the root CA's public key, but the wording in the docs suggests it should include multiple keys.

Am I able to use mTLS with nats.rs?

**Comment by stjepang** [comment]
The Rust client passes the certificate to [`RootCertStore::add_pem_file()`](https://docs.rs/rustls/0.18.1/rustls/struct.RootCertStore.html#method.add_pem_file). So it's a PEM file containing root certificate(s).

I suppose what you need is [`ClientConfig::set_single_client_cert()`](https://docs.rs/rustls/0.18.1/rustls/struct.ClientConfig.html#method.set_single_client_cert), isn't it? We could either a method with the same name to the `nats::Options` type, or maybe even allow passing a `ClientConfig` directly to it. In the latter case, breaking changes to `rustls` would require us to make a breaking change to the `nats` crate. Do you have any preference here?

**Comment by andrewbanchich** [comment]
No preference from my end. Thank you!
