### ISSUE TITLE
Sync TLS authetication missing ECKey handling

### ISSUE THREAD

**Issue by sp-angel** [nats-io/nats.rs#1126]
### What version were you using?
version = "0.24.0"

### Description
Testing mTLS connections to TLS-enabled NATS server using EC key, the following error message is issued at the moment  `connect()` is called:

`could not find client key in the path`

Looking into the code I see that `load_key()` function in [nats/src/auth_utils.rs](https://github.com/nats-io/nats.rs/blob/57a956a647e31b8335c65507e326323647abd19a/nats/src/auth_utils.rs#L122) is missing `ECKey` handling.

That is correct in the corresponding async code in [async-nats/src/tls.rs](https://github.com/nats-io/nats.rs/blob/57a956a647e31b8335c65507e326323647abd19a/async-nats/src/tls.rs#L50)

Fixing it locally resolved the issue.

### What environment was the server running in?

Ubuntu 20.04.6 LTS

### Is this defect reproducible?

Yes.

Set a NATS server with TLS enabled using EC keys 
```
$ openssl pkey -in nats-certificate-secret.tls.key -text -noout
...
ASN1 OID: prime256v1
NIST CURVE: P-256
```

NATS server
```
nats-server -D -V --tls --tlscert=nats-certificate-secret.tls.crt --tlskey=nats-certificate-secret.tls.key --tlscacert=ca.crt --tlsverify
```

run client using
```
let nats_option = nats::asynk::Options::new().client_cert(nats_cert_path, nats_key_path).add_root_certificate(nats_ca_path)
let nats_connection = nats_option.connect(&connect_string).await.unwrap();
```

### Given the capability you are leveraging, describe your expectation?

That should open the connection with the server without error

### Given the expectation, what is the defect you are observing?

Get an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "could not find client key in the path" }', examples/nats.rs:xx:yy
```

**Comment by Jarema** [comment]
Thanks for filling out the issue!

If you have a working fix, would you mind opening a PR?

Please keep in mind that sync nats client is a legacy one. async-nats is recommended.

**Comment by sp-angel** [comment]
Thanks! Yup, we have some code that's still using the sync one :slightly_smiling_face: 

Got PR: https://github.com/nats-io/nats.rs/pull/1128
