### ISSUE TITLE
Request::respond() consumes `self`, making it tricky to work with in some contexts

### ISSUE THREAD

**Issue by jlandahl** [nats-io/nats.rs#1138]
### What motivated this proposal?

I've been using async-nats for a couple of months for basic publish/subscribe functionality, and now I'm trying to add request/response functionality. I've written my application in such a way that I abstract out the various messaging features using traits, with concrete implementations for the various NATS types. This is for both testability (I can pass in test versions of the traits in tests), flexibility (I can swap in or out messaging providers for different purposes), and isolation (I don't have vendor-specific types and code in my business logic). This means dynamic dispatch and boxing, but it's an acceptable trade-off for this application.

Now that I'm adding publish/subscribe, I've gotten to the point of abstracting `async_nats::service::Request` [here](https://github.com/nats-io/nats.rs/blob/f115488960c7e1b3b57c232a57ddbc8f8ec4c85e/async-nats/src/serviceh/mod.rs#L719) behind a generic trait. This involves my `Service` trait's `endpoint()` function returning a `Box<dyn Request>` (where `Request` is my trait), which on its own works fine.

The trouble is that `async_nats::service::Request::respond()` consumes `self`, so as far as I know my interface must do the same, and when I call my `respond()` from client code I get the following compiler error: "cannot move a value of type `dyn messaging::Request` / the size of `dyn messaging::Request` cannot be statically determined".

I'm still quite new to Rust, so I could be going about this the wrong way, but in looking at the code for `async_nats::service::Request::respond()`  I don't immediately see why it needs to consume `self` rather than take a reference.

### What is the proposed change?

Change `self` to `&self` [here](https://github.com/nats-io/nats.rs/blob/f115488960c7e1b3b57c232a57ddbc8f8ec4c85e/async-nats/src/service/mod.rs#L738).

### Who benefits from this change?

This benefits anyone using `async_nats::service::Request::respond()` who can't move the original `Request` value for one reason or another.

### What alternatives have you evaluated?

I'm still working on alternatives, and would appreciate any suggestions from people with a lot more experience with Rust than me.

**Comment by jlandahl** [comment]
Quick update: I forked the repo, added the `&` in the right place, compiled it locally, and everything seems to be working as expected.

**Comment by Jarema** [comment]
Thanks for fillkng up the issue!

The main reason for `respond` to take self was to avoid calling it twice, and I have to think if we want to change it.
It might be ok. 
I will get back to you shortly.

**Comment by Jarema** [comment]
Closing, as PR has been merged.
