### ISSUE TITLE
Deplicated Message Even When `NATS_MESSAGE_ID` is the same.

### ISSUE THREAD

**Issue by Migorithm** [nats-io/nats.rs#1142]
### Observed behavior

When sending exactly the same message payload with the same header, it deduplicates message accordingly.

(I configured `duplicate_window` too.) 

### Expected behavior

Unlike what it said on [here](https://docs.nats.io/using-nats/developer/develop_jetstream/model_deep_dive#message-deduplication), when I changed the contents of a payload, it kept sending a message. 

I expect even though it is a different payload when the message id header is the same, it should be sent only once. 

### Server and client version

0.32.1

**Comment by Jarema** [comment]
Thank you for reporting the issue!

Your expectation is correct.

I tested it and it behaves correctly. No matter if payload is the same or different.
Server tracks only those ids for deduplication. It does not care about the payload.
Can you show example of a code that has this behavior?

**Comment by Jarema** [comment]
@Migorithm can you provide the requested info?

**Comment by Jarema** [comment]
@Migorithm I'm closing this issue as neither can I reproduce this, nor there is requested additional info.
Feel free to reopen it if you get time to get back to this.
