### ISSUE TITLE
0.8.1 publishing misses messages

### ISSUE THREAD

**Issue by andrewbanchich** [nats-io/nats.rs#116]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ x ] Included below version and environment information
 - [ x ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)

0.8.1

#### rustc version (`rustc --version` - we support Rust 1.37 and up)

1.47

#### OS/Container environment:

macOS (Rust bin) / Docker (NATS)

After upgrading to 0.8.1, although [`Connection::publish`](https://docs.rs/nats/0.8.1/nats/asynk/struct.Connection.html#method.publish) returns `Ok`, not all messages make it to the NATS server. If I send several thousand messages, around 20 are missing every time, each time varying slightly. Even with sending 3 messages total, the server receives only 1.

I'm using JetStream, so to debug this I went into the JetStream container and ran `nats --tlsca=/certs/ca.pem --tlscert=/certs/nats.pem --tlskey=/certs/nats-key.pem str info MYSTREAM`:

```
Messages: 1
               Bytes: 429 B
            FirstSeq: 1 @ 2020-10-21T03:19:52 UTC
             LastSeq: 1 @ 2020-10-21T03:19:52 UTC
    Active Consumers: 1
```

This was after publishing 3 messages. I matched on the result of `nc.publish` and logged whether it was `Ok` or `Err`, and saw 3 `Ok` logs.

I then downgraded nats.rs to 0.7.4 and went through the same tests, and it doesn't have the same problem; all the numbers match up every time.

I couldn't test on 0.8.0 because every attempt to create a `Connection` just hangs forever.

**Comment by stjepang** [comment]
> I couldn't test on 0.8.0 because every attempt to create a `Connection` just hangs forever.

This is a known problem with TLS that was resolved by #107 in v0.8.1.

In an attempt to reproduce, I ran the following:

```rust
let nc = nats::Options::new()
    .connect("tls://demo.nats.io:4443")
    .unwrap();
let sub = nc.subscribe("foo").unwrap();
let t = std::thread::spawn(move || {
    for i in 0..1_000_000_000_u64 {
        assert_eq!(sub.next().unwrap().data, i.to_le_bytes());
    }
});
for i in 0..1_000_00_000_u64 {
    nc.publish("foo", i.to_le_bytes()).unwrap();
}
t.join().unwrap();
```

No messages seem to be lost. Not sure if the problem occurs only with JetStream - I'm going to try that now.

**Comment by andrewbanchich** [comment]
I tested against NATS and JetStream and NATS lost the same number of messages for me.

**Comment by stjepang** [comment]
When done with publishing messages, do you call `Connection::flush()` or `Connection::close()` to make sure that all messages reach the server?

**Comment by andrewbanchich** [comment]
Nope, I haven't been doing that.

**Comment by stjepang** [comment]
I wonder if that may be the issue. Before v0.8.1, dropping `Connection` did nothing so the client thread would be leaked, which means it would keep working in the background (e.g. sending published messages to the server).

In v0.8.1, dropping `Connection` stops that client thread, so if you forget to call `flush()` or `close()`, buffered published messages get lost and won't reach the server.

**Comment by andrewbanchich** [comment]
Yep, that must be what happened! It works when I call `nc.flush()`. Thank you so much for your help!

Out of curiosity, any thoughts on having the `Connection` automatically flush on drop?

**Comment by stjepang** [comment]
Note that the async API (`nats::asynk::Connection`) cannot flush automatically on drop because flushing is an async operation, while dropping is synchronous. Rust designers are thinking about async drop so it might become a possibility in the future: http://smallcultfollowing.com/babysteps/blog/2020/03/10/async-interview-7-withoutboats/#next-step-async-destructors

It would be fine to flush on drop in `nats::Connection`, though. In fact, `std::fs::File` flushes on drop (potentially a blocking operation) so there is already precedent in the standard library implying blocking in drop is okay. If we decide to flush when `nats::Connection` is dropped, there would be discrepancy between sync and async APIs - a potential trap for bugs because someone might assume the async API flushes on drop too.

In the end, I don't really have strong opinions and it isn't obvious to me on what the right solution here is - there are drawbacks either way.

**Comment by derekcollison** [comment]
Originally I did not want folks to have to do anything additional on simple cases. The connection should be dropped as we exit and that should try to flush out any pending before it returns.

A simple publisher should create connection, publish and exit letting connection drop and flush..
