### ISSUE TITLE
`FetchBuilder::max_messages` upper limit too high

### ISSUE THREAD

**Issue by pmajocha** [nats-io/nats.rs#1175]
### Observed behavior

When supplied with `FetchBuilder::max_messages(usize::MAX)` the builder doesn't error. Upon polling the fetcher for messages it errors with `Custom { kind: Other, error: "error while processing messages from the stream: 400, Some(\"Bad Request - json: cannot unmarshal number 18446744073709551615 into Go struct field JSApiConsumerGetNextRequest.max_bytes of type int\")" }`. 

### Expected behavior

The function shouldn't take higher value than Go can take.

### Server and client version

nats 2.9, async-nats 0.33.0

**Comment by Jarema** [comment]
Thanks for reporting the issue!

Keep in mind that this can error in other cases too: if server/cluster has set max pull request batch size for example.

What was the reason to pass such value? Batch size in realistic scenarios should be between 1 and few hundreds, sometimes to few k of messages. Bigger values does not make much sense and should use `stream` or `consume` methods that will make a performant interleaved fetch requests.

**Comment by pmajocha** [comment]
Testing purposes, I wanted to fetch as many messages as possible from the stream and check whether the number of messages is correct. Couldn't find anything like it, at least on the first glance. Could you link those `stream` and `consume` methods?

**Comment by Jarema** [comment]
Sure!

You can use [consume](https://docs.rs/async-nats/latest/async_nats/jetstream/consumer/struct.Consumer.html#method.messages) on any consumer.

To quickly whip through messages on disposable consumer, you can use [ordered consumer](https://docs.rs/async-nats/latest/async_nats/jetstream/consumer/pull/struct.OrderedConfig.html).

I'm closing this issue, as things migh change in the server and this value is not part of any contract, while it can error anyway with lower account max values.
