### ISSUE TITLE
NATS publish silently fails

### ISSUE THREAD

**Issue by segfaultdoc** [nats-io/nats.rs#1177]
### Observed behavior

Steps to repro:
1. Start nats-server (2.9.14)
2. Run a publisher (async-nats/0.33.0)
3. Tear down server

Even after the service is torn down the publish returns `Ok(())`.

### Expected behavior

Should return some type of connection error.

### Server and client version

nats-server (2.9.14)
nats.rs (async-nats/0.33.0)

**Comment by Jarema** [comment]
Thanks for reporting the issue.

Can you provide more details?
By service you mean the `nats-server`?

Keep in mind that all NATS clients will buffer messages hoping that the connection will be resumed, which is the typical scenario. The buffer size is [configurable](https://docs.rs/async-nats/latest/async_nats/struct.ConnectOptions.html#method.client_capacity).

You can track the connection state by the `events` [connection option](https://docs.rs/async-nats/latest/async_nats/struct.ConnectOptions.html#method.request_timeout)

**Comment by segfaultdoc** [comment]
> Thanks for reporting the issue.
> 
> Can you provide more details? By service you mean the `nats-server`?
> 
> Keep in mind that all NATS clients will buffer messages hoping that the connection will be resumed, which is the typical scenario. The buffer size is [configurable](https://docs.rs/async-nats/latest/async_nats/struct.ConnectOptions.html#method.client_capacity).
> 
> You can track the connection state by the `events` [connection option](https://docs.rs/async-nats/latest/async_nats/struct.ConnectOptions.html#method.request_timeout)

Yea by service meant nats-server. Thanks for the color there. Can close this issue
