### ISSUE TITLE
docs for `ConnectOptions::retry_on_initial_connect`

### ISSUE THREAD

**Issue by barafael** [nats-io/nats.rs#1180]
### Proposed change

This function should be documented.

### Use case

IMHO this function could use some documentation.

### Contribution

yes

**Comment by Jarema** [comment]
Hi! Thanks for catching that one not having docs.

If you are willing to contribute that would be awesome!

Here is a reference doc for this option in ADR: https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-40.md#retry-on-failed-initial-connect

If you need any help - don't hesitate to ask.
Just follow other docs for options and add an example.

**Comment by barafael** [comment]
@Jarema See https://github.com/nats-io/nats.rs/pull/1181

**Comment by barafael** [comment]
This may be closed.
