### ISSUE TITLE
max_reconnects not configurable in ConnectOptions

### ISSUE THREAD

**Issue by glueball** [nats-io/nats.rs#1186]
### Observed behavior

The ConectOptions struct has the max_reconnects field, defaulting to Some(60), but no method to configure it.

### Expected behavior

A method .max_reconnects allows configuring the value.

### Server and client version

async_nats 0.33

### Host environment

N/A

### Steps to reproduce

N/A

**Comment by Jarema** [comment]
Thanks for filling the issue and the PR!

Will be reviewed soon.

**Comment by Jarema** [comment]
Fixed in #1188
