### ISSUE TITLE
Add `create` for async-nats KV

### ISSUE THREAD

**Issue by praveenperera** [nats-io/nats.rs#1204]
### Proposed change

The go library seems to have the `Create` function which succeeds to add a value for a key if it’s not set, or if the last operation was a delete. 

However, the async-nats rust package seems to missing it.

```go
// Create will add the key/value pair if it does not exist.
Create(key string, value []byte) (revision uint64, err error)
```

### Use case

Leases / Distributed lock

### Contribution

Yes

**Comment by Jarema** [comment]
Hey!

Thanks for creating the proposal.

**Comment by Jarema** [comment]
el

**Comment by praveenperera** [comment]
@Jarema I was looking at how its implemented in the go SDK. And the update with `0` revision makes sense.

But I'm not sure how to implement `Create` if it was deleted. In the go SDK it looks for `ErrKeyDeleted` error type, I wasn't able to find the equivalent error in Rust. Maybe I missed something?

**Comment by praveenperera** [comment]
@Jarema made a draft PR
