### ISSUE TITLE
It would be handy to be able to get a clone of the NATS Client out of a Service.

### ISSUE THREAD

**Issue by dtessman** [nats-io/nats.rs#1208]
### Proposed change

Add a public function that returns a clone of the client field of the Service struct.  Or, make the client field of the Service struct public.

### Use case

I am moving an instance of the Service struct as a "context" through a hierarchy of methods so it is available for use by lower functions.  Because I have to do other NATS oriented stuff within those methods as well, I need to track and pass both the original NATS Client that created the Service instance and the Service instance itself.  It would be very nice to just be passing the Service instance around and be able to extract the NATS Client from the Service instance itself as needed.

### Contribution

I can certainly post a PR.  But it is pretty trivial.

**Comment by Jarema** [comment]
Hey. Can you give an example when you need `Client` when working with `Service` API?

**Comment by dtessman** [comment]
Sure, np.  I have built a layer on top of a service that not only receives, but also performs requests out to other services.  This is instantiated by the developer as a structure with a typical "new" method.   I pass the service into the new method so that the structure knows who it is by the service name obtained through the info() method on the service.  It also establishes a group and opens some endpoints.  However to perform outbound service calls, the structure also needs a NATS client.  So unless I want the structure to use a global client (ick), I need to pass the NATS client into the structure as well.  So now I have two objects I need to pass in when instantiating the structure. It would just be nice to be able to just pull the client from the service and have only a single item (the service) to pass around.  Not a biggie, but a nice to have.

**Comment by Jarema** [comment]
Thanks for understanding!

I'm closing this for now.
We will consider making client public in the future iterations of Service API.
