### ISSUE TITLE
Infinite hang with stream name is invalid

### ISSUE THREAD

**Issue by nickgerace** [nats-io/nats.rs#1213]
### Observed behavior

When a stream name contains a `.`, there is an infinite hang when calling [`get_or_create_stream`](https://docs.rs/async-nats/0.33.0/async_nats/jetstream/context/struct.Context.html#method.get_or_create_stream). In the config, the name is `<stream>.<name>` and the subjects are a `Vec` of one element: `<stream>.<name>.>`.

### Expected behavior

The [upstream docs](https://docs.nats.io/running-a-nats-service/nats_admin/jetstream_admin/naming) indicate that including `.` in the stream name is invalid, but I would have expected an error instead of a hang.

### Server and client version

Server (Docker): `2.10.10`
Rust crate: `0.33.0`

### Host environment

Linux (GNU) `6.6.10` on `x86_64`

### Steps to reproduce

Call [`get_or_create_stream`](https://docs.rs/async-nats/0.33.0/async_nats/jetstream/context/struct.Context.html#method.get_or_create_stream) with `.` in the stream name.

**Comment by nickgerace** [comment]
I understand that the configuration isn't validated for this method based on the docs, but I still would have expected an error rather than a hang.

**Comment by Jarema** [comment]
Hey. 
Thanks for filling the issue.
Yes, we can definately validate that and throw an error.

**Comment by nickgerace** [comment]
Thank you @Jarema!
