### ISSUE TITLE
MAINTAINERS please release

### ISSUE THREAD

**Issue by ekalosak** [nats-io/nats.rs#1224]
### Observed behavior

0.33 is 5 months old, it'd be good to have latest main in at least a -dev release?

### Expected behavior

For building trust in this client lib, seems like a healthier release cycle would be monthly? Any internal or community plans for keeping consistent?

### Server and client version

elided

**Comment by Jarema** [comment]
Release will happen on monday.

We were waiting for rustls release and making sure that red CI is not a client issue.

Yes, we usually stick to more often releases.

Sorry for the delay.

**Comment by Jarema** [comment]
new version has been released #1228
