### ISSUE TITLE
Client vs Jetsream Context

### ISSUE THREAD

**Issue by jadamcrain** [nats-io/nats.rs#1226]
### Proposed change

Jetstream `Context` is just a thin clone-able layer on top of core Client, however, you can't access Client after you create a `Context`.

Even though Client is `Clone`, it would be nice to be not have to do so when I already have a client inside of `Context`.

### Use case

Often, I need to access core NATS, service API, and Jetstream all within the same component.

**Comment by Kinrany** [comment]
Why does JetStream need a separate context, why isn't a single Client enough?

**Comment by Jarema** [comment]
@Kinrany it's just a struct that holds given JS context config - mainly it's `domain` and `JS.API.prefix`, as this is how you interact with JetStream. It does not have any overhead.

**Comment by Kinrany** [comment]
Perhaps Client could have a type state and optionally include the JS context config?

**Comment by Jarema** [comment]
You may want to use many (usually two) JetStream contexts with one NATS connection (in Hub & Spoke topologies), so the current approach seems most feasible.

**Comment by Kinrany** [comment]
That makes sense, thank you!

**Comment by Jarema** [comment]
Great that your questions are answered!
I'm closing the issue.
Feel free to reopen if you think it should be discussed more.
