### ISSUE TITLE
Update ring to 17.x

### ISSUE THREAD

**Issue by Revertron** [nats-io/nats.rs#1230]
### Proposed change

Please, update `ring` dependency to 17.x.

### Use case

There are new supported architectures, so we will get it for a low price.

**Comment by Jarema** [comment]
It is already v17. Just not released yet.
Please consider moving to the new async client, as the sync one is deprecated and is not getting new features.

**Comment by Revertron** [comment]
But I don't want to get whole tokio in my project, it works without asyncs perfectly well.

**Comment by Jarema** [comment]
both sync and async client are now released with updated version of Ring.
