### ISSUE TITLE
Add at-least-once KV watch method

### ISSUE THREAD

**Issue by AbstractiveNord** [nats-io/nats.rs#1233]
### Proposed change

Add new method for KV watch with at least once guarantee.

### Use case

Same cases as watch command, when at most once guarantee is not enough.

### Contribution

Yes.

**Comment by Jarema** [comment]
Watch is not at most once.
It uses the Ordered Consumer under the hood.
That means that every message in the stream will be delivered exactly once per watch according to deliver policy (though this is not actual exactly once processing guarantee, as that requires no duplicates on publisher end. Its exactly once per watcher instance).

**Comment by AbstractiveNord** [comment]
> Watch is not at most once. It uses the Ordered Consumer under the hood. That means that every message in the stream will be delivered exactly once per watch according to deliver policy (though this is not actual exactly once processing guarantee, as that requires no duplicates on publisher end. Its exactly once per watcher instance).

Oh, nice, missed this. Sorry about that.
