### ISSUE TITLE
Documentation for JetStream Messages needs clarification

### ISSUE THREAD

**Issue by ajlane** [nats-io/nats.rs#1244]
### Observed behavior

I couldn't find the redelivery count for JetStream. Asking on Slack (https://natsio.slack.com/archives/CM3T6T7JQ/p1712473508907169?thread_ts=1712472176.528409&cid=CM3T6T7JQ), it was suggested that the documentation doesn't correctly describe the field that provides it.

In particular, the delivered field on https://docs.rs/nats/latest/nats/jetstream/struct.JetStreamMessageInfo.html does not describe a per message redelivery count.

### Expected behavior

Docs correctly and unambiguously describe the purpose of metadata fields.

### Server and client version

latest

**Comment by ajlane** [comment]
Brilliant. Might need to check the one in async-nats too?

https://docs.rs/async-nats/latest/async_nats/jetstream/message/struct.Info.html#structfield.delivered

**Comment by Jarema** [comment]
@ajlane I updated both.
