### ISSUE TITLE
docs.rs build broken

### ISSUE THREAD

**Issue by jaskij** [nats-io/nats.rs#1257]
### Observed behavior

![image](https://github.com/nats-io/nats.rs/assets/1429132/dc96e7eb-5d65-4172-89ff-666f6cba7546)

### Expected behavior

Working documentation at docs.rs

### Server and client version

async-nats 0.35

### Host environment

n/a

### Steps to reproduce

Visit https://docs.rs/crate/async-nats/latest

**Comment by Jarema** [comment]
Thanks for the report.
I think it's because of aws lcs fips trying to create cache during the build.
Working on it.

**Comment by Jarema** [comment]
Released v0.35.1 which fixes the issue.
