### ISSUE TITLE
Subscription capacity documentation or implementtion value is incorrect

### ISSUE THREAD

**Issue by nazar-pc** [nats-io/nats.rs#1275]
### Observed behavior

`ConnectOptions::subscription_capacity` documentation says "Default is set to 1024 messages buffer":
https://github.com/nats-io/nats.rs/blob/f86dce921fad45ece9f06e9ddbf72a6ef085125a/async-nats/src/options.rs#L607-L625

However, the actual implementation is `1024*64` for some reason:
https://github.com/nats-io/nats.rs/blob/f86dce921fad45ece9f06e9ddbf72a6ef085125a/async-nats/src/options.rs#L107

### Expected behavior

Documentation and implementation must match

### Server and client version

async-nats 0.35.1

**Comment by Jarema** [comment]
The capacity is bigger as that yields quite substantial boost in performance.
'are you interested in contributing the fix to the docs?
