### ISSUE TITLE
Inner Tcp configuration

### ISSUE THREAD

**Issue by BijanVeyssi** [nats-io/nats.rs#1320]
### Proposed change

I would like to be able to configure the [write and read timeout](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_read_timeout) of the inner TCP stream.

### Use case

I am working on a embedded project connected to a nats server that needs to have a high reactivity to disconnection.

### Contribution

I can propose an implementation to add this feature if needed.

**Comment by Jarema** [comment]
In Tokio, it's probably not a great idea to use the read and write timeouts.
Additionally, on stale connections you anyway should rely on ping, which you can tweak via https://docs.rs/async-nats/latest/async_nats/struct.ConnectOptions.html#method.ping_interval

**Comment by BijanVeyssi** [comment]
I tested, and it properly detects the disconnection with reasonable delay now. Sorry, I should have checked the disconnection mechanism with more attention. Have a nice day.

**Comment by Jarema** [comment]
No worries! Happy it works as expected for you.
