### ISSUE TITLE
Static Connection doesn't flush messages

### ISSUE THREAD

**Issue by andrewbanchich** [nats-io/nats.rs#134]
#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)

name = "nats"
version = "0.8.6"

#### rustc version (`rustc --version` - we support Rust 1.37 and up)

rustc 1.49.0 (e1884a8e3 2020-12-29)

#### OS/Container environment:

Pop OS (Debian Linux)

#### Steps or code to reproduce the issue:

Create a static NATS Connection using `once_cell::sync::Lazy`:

```
pub static NATS: Lazy<nats::asynk::Connection> = Lazy::new(|| {
    let nats_host = std::env::var("NATS_HOST").unwrap();

    let nc = nats::Options::new()
        .add_root_certificate(format!("{}/ca.pem", *CERT_DIR))
        .connect_async(&nats_host);

    smol::block_on(nc).expect("Couldn't connect to NATS")
});
```

In a stream, publish messages using the static `NATS` Connection and flush:

```
\\ inside stream.for_each

if let Err(e) = NATS.publish(&sub, &serde_json::to_vec(&foo).unwrap()).await {
    error!("Couldn't publish message: {:#?}", e);
}

NATS.flush().await.unwrap();
```

Some messages are not published.

Switch to create new NATS Connection instead of using static:

```
\\ inside stream.for_each

let nc = nats::Options::new()
    .add_root_certificate(format!("{}/ca.pem", std::env::var("CERT_DIR").unwrap()))
    .connect_async(&std::env::var("NATS_HOST").unwrap())
    .await
    .expect("Couldn't connect to NATS");

if let Err(e) = nc.publish(&sub, &serde_json::to_vec(&foo).unwrap()).await {
    error!("Couldn't publish message: {:#?}", e);
}

nc.flush().await.unwrap();
```

All messages are now published.

#### Expected result:

I'd like to share a static NATS Connection across my program and have it send all messages.

**Comment by spacejam** [comment]
This sounds like expected NATS behavior when connecting to a cluster where a subject has not yet propagated fully. I believe that it simply worked the second time because the subject in question had propagated. Lazy static functionality has no impact on NATS functionality.

**Comment by andrewbanchich** [comment]
@spacejam I've tested this multiple times, and each time was publishing to a new subject.

**Comment by andrewbanchich** [comment]
Also, as a side question, why is it expected to miss publishing messages at all? Even if I were running a cluster, if I'm subscribed to `FOO.*` shouldn't I expect to receive all messages from `FOO.bar`? How can I prevent messages being missed?

**Comment by spacejam** [comment]
Without the requested bug template reproduction fields there's no way for us to show you where the bug is, but I am doubtful that this is a bug related to the standard library's Lazy functionality. In general, using async causes a lot of strange issues due to not knowing when asynchronous logic is actually being executed, which is one of the reasons why I prefer to avoid it.

I recommend trying out the latest version, and avoiding async to see if you can get the same issue to pop up or not, and if not, finding where the async version is being scheduled in a way that causes your expected behavior not to happen.

**Comment by andrewbanchich** [comment]
> I am doubtful that this is a bug related to the standard library's Lazy functionality.

Just to be clear, I'm referring to `oncecell::sync::Lazy`, not something in the standard library.

> I recommend trying out the latest version, and avoiding async to see if you can get the same issue to pop up or not, and if not, finding where the async version is being scheduled in a way that causes your expected behavior not to happen.

I will test out the latest version as soon as I get a chance, but I would prefer using async. Concurrency is important to us, and a good deal of our code is async already. Furthermore, I would think that if the issue is solved by using a blocking client, that would mean there is a bug in the async client.

> Usually, this is happening when you are not actually awaiting some async task that you created but never caused to be scheduled. This lazy scheduling of async is the root of a lot of bugs.

I'm didn't change any await points in the rest of my codebase, and cargo warns you if you are missing an `await`. I don't have any warnings from cargo.

> NATS is generally at-most-once and reliability needs to be built on-top. Jetstream is recommended if you require more guarantees about delivery. Sometimes in clustered environments subscriptions take a moment to propagate between nodes, just as a published message does. There have been some tricks to optimistically push messages in some situations but I believe normal publishes can sometimes experience a bit of a hiccup initially as subscription interest propagates through the cluster.

I'm not using a cluster. It's a single, local instance of NATS. Furthermore, my subscribers are listening on the subject pattern long before the messages are published. From what I understand, the subscription interest for `FOO.*` would be propagated to the cluster first, and that is all that is required to ensure all published messages to `FOO.bar` are received by any subscribers. Is that correct?

I don't think this issue should have been closed since from what I understand, it is pretty clearly not related to propagating a subject, and the issue has not been resolved.

**Comment by spacejam** [comment]
Can you provide a complete, minimized code example that reproduces the issue?

**Comment by andrewbanchich** [comment]
Thanks for reopening. I'll try to do that as soon as I have a chance.

**Comment by andrewbanchich** [comment]
Just tested 0.9.1 and this issue is resolved. Thanks!
