### ISSUE TITLE
Excessive PAF Resolution Time During JetStream Server Restarts or Transient Errors

### ISSUE THREAD

**Issue by yhl25** [nats-io/nats.rs#1348]
### Observed behavior

When publishing messages to JetStream using publish, the PAFs take around 5 seconds each to resolve if the server is restarted or encounters transient errors. This leads to significant delays if multiple PAFs are queued.

### Expected behavior

PAFs should resolve within a reasonable time even during transient errors or server restarts, without causing excessive delays.

### Server and client version

Server: 2.10.22
Client: v0.37.0

### Steps to reproduce

1. Connect to NATS server.
2. Publish to a JetStream stream using the code below.
3. Set PAF channel size to 10,000.
4. Restart the JetStream server during publication.
5. Observe PAF resolution times.

Publish Code Snippet:
```rust
use std::{
    time::{ SystemTime, UNIX_EPOCH},
};
use anyhow::{Context, Result};
use async_nats::{
    jetstream::{self, context::Publish},
};
use bytes::Bytes;
use rand::RngCore;
use tokio::{sync::mpsc};
use tokio::time::Instant;
use tracing::error;

mod metrics;

const STREAM_NAME: &str = "js-benchmark";

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt().with_ansi(false).init();
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("Failed to install rustls crypto provider");
    if let Err(e) = run().await {
        error!(?e, "Consumer failed");
    }
}

async fn run() -> Result<()> {
    let client = async_nats::connect("nats://localhost:4222")
        .await
        .context("Connecting to NATS server")?;
    let js_client = jetstream::new(client);

    let mut rng = rand::thread_rng();

    let (tx, mut rx) = mpsc::channel(1000);
    tokio::spawn(async move {
        while let Some(pub_ack_fut) = rx.recv().await {
            let failed_paf_time = Instant::now();
            if let Err(e) = pub_ack_fut.await {
                error!(?e, "Failed to publish message after {:?}", failed_paf_time.elapsed());
            }
        }
    });

    loop {
        let mut payload: Vec<u8> = vec![0; 128];
        rng.fill_bytes(&mut payload);

        let pub_ack_fut = js_client
            .send_publish(
                STREAM_NAME,
                Publish::build()
                    .payload(Bytes::from(payload))
                    .message_id(generate_message_id()),
            )
            .await
            .context("Publishing message")?;
        tx.send(pub_ack_fut).await?;
    }
}

fn generate_message_id() -> String {
    let start = SystemTime::now();
    let since_the_epoch = start
        .duration_since(UNIX_EPOCH)
        .expect("Time went backwards");
    since_the_epoch.as_nanos().to_string()
} 
```

<details> 
<summary>Logs</summary>
<pre><code>
2024-11-25T08:57:06.753667Z  INFO async_nats: event: client error: nats: IO error
2024-11-25T08:57:07.401827Z ERROR producer: Failed to publish message after 5.002262666s e=Error { kind: TimedOut, source: None }
2024-11-25T08:57:10.757114Z  INFO async_nats: event: client error: nats: IO error
2024-11-25T08:57:12.403425Z ERROR producer: Failed to publish message after 5.001471s e=Error { kind: TimedOut, source: None }
2024-11-25T08:57:14.760990Z  INFO async_nats: event: client error: nats: IO error
2024-11-25T08:57:17.405424Z ERROR producer: Failed to publish message after 5.001843417s e=Error { kind: TimedOut, source: None }
2024-11-25T08:57:18.770246Z  INFO async_nats: event: client error: nats: IO error
2024-11-25T08:57:22.407420Z ERROR producer: Failed to publish message after 5.001836667s e=Error { kind: TimedOut, source: None }
2024-11-25T08:57:22.774730Z  INFO async_nats: event: client error: nats: IO error
2024-11-25T08:57:26.778654Z  INFO async_nats: event: client error: nats: IO error
2024-11-25T08:57:27.411999Z ERROR producer: Failed to publish message after 5.004424792s e=Error { kind: TimedOut, source: None }
2024-11-25T08:57:30.782945Z  INFO async_nats: event: client error: nats: IO error
</code></pre>
</details>

**Comment by yhl25** [comment]
Is it not a good practice to put the PAFs in a channel and resolve them as shown in the code snippet, and would it be better to spawn a Tokio task for each PAF while controlling the number of concurrent tasks to manage load effectively?

**Comment by Jarema** [comment]
Probably the most efficient way is to use `futures::stream::FuturesUnordered`.

PAF is simply a request/response pattern. If the connection is re-established, there is a high chance that some responses will be lost. If it was because of the server restart, than they were for sure lost, but client has no way of detemining why the connection was down, so those PAFs just time out.
You can change the timeout values if you want shorter ones.

**Comment by Jarema** [comment]
I'm closing this one, as don't think there is any issue present.
Feel free to reopen, or open or comment if you would like to follow up.
