### ISSUE TITLE
Performance hit in proto::decode due to `to_uppercase()` call

### ISSUE THREAD

**Issue by tekjar** [nats-io/nats.rs#139]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included below version and environment information
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
0.9.1

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
1.48

#### OS/Container environment:
Linux (Pop Os 20.04)

#### Steps or code to reproduce the issue:
Run the code in this [gist](https://gist.github.com/tekjar/441901712f1e1206202ad06cef4241ad)

![image](https://user-images.githubusercontent.com/6826529/105066839-30d06700-5aa5-11eb-92e0-324d5d888efe.png)

Fix:

Removing upper case conversion [here](https://gist.github.com/tekjar/441901712f1e1206202ad06cef4241ad#file-natsthroughput-rs-L230) fixes the problem. Throughput is good after that.

**Comment by spacejam** [comment]
Is this using a debug build or are release optimizations enabled?

**Comment by tekjar** [comment]
@spacejam This is release build
