### ISSUE TITLE
error encountered in the parser read_loop

### ISSUE THREAD

**Issue by dwaynebradley** [nats-io/nats.rs#14]
I'm able to create a connection, subscribe to my topic (with a subscription handler) and see data flowing but when I go to close the app and clean up I'm getting an error.

First thing I'm doing is calling `unsubscribe` on my handler like this:

```rust
    match nsh.unsubscribe() {
        Ok(_ok) => {
            println!("NATS unsubscribe() successful!");
        }
        Err(e) => {
            println!("NATS unsubscribe() failed!!! {}", e);
        }
    };
```

I see the `NATS unscribe() successful!` message like I'm expecting.

Immediately after I unsubscribe, I `close` the connection like this:

```rust
    match nc.close() {
        Ok(_ok) => {
            println!("NATS connection close() successful!");
        }
        Err(e) => {
            println!("NATS connection close() failed!!! {}", e);
        }
    }
```

Before I see the `NATS connection close() successful!` message, I get the `parsing error`. Here is what that output looks like:

```
NATS unsubscribe() successful!
error encountered in the parser read_loop: Custom { kind: InvalidInput, error: "parsing error" }
NATS connection close() successful!
```

Is there something that I'm not doing correctly when cleaning up my connection and subscription?

**Comment by derekcollison** [comment]
No I believe this is a spurious print from something we need to parse. I am confident it's benign. Will fix.
