### ISSUE TITLE
trouble with the jetstream::Consumer::pull method

### ISSUE THREAD

**Issue by sech9446** [nats-io/nats.rs#163]
I have a trouble while using the `jetstream::Consumer::pull` method.

The doc said this method is only usable with pull-based consumers, which means `ConsumerConfig.deliver_subject` must be `None`.

However, if I try to use it with pull-based consumers, it complains the `deliver_subject` should not be `None`. 

Maybe a bug?

https://github.com/nats-io/nats.rs/blob/e3fb52de4c1c2152f31ff3ad6222baa3c20532f7/src/jetstream.rs#L986-L1013

**Comment by spacejam** [comment]
Thank you for opening this issue! I've just released version 0.9.9 which includes a fix.
