### ISSUE TITLE
Error when connecting to NATS v2.1.0

### ISSUE THREAD

**Issue by whmountains** [nats-io/nats.rs#17]
I'm unable to connect to NATS v2.1.0 with this client.  NATS v2.1.4 works fine.  It just so happened that I had v2.1.0 installed on my production server, and v2.1.4 on my local machine.

The error messages I get is:

```
 missing field `server_name` at line 1 column 186
```

And indeed, telnet confirms that this field is missing.  The dotnet client doesn't have this issue, so that makes me thing the client is being overly strict.  But I'm open to calling it an already-fixed in the server.  I will be definitely updating my server in either case.

**Comment by derekcollison** [comment]
Yes it is being overly strict, will fix. Thanks!

**Comment by derekcollison** [comment]
ok fixed, will wait on @spacejam to push new release to crates.io

**Comment by whmountains** [comment]
Awesome, thanks!
