### ISSUE TITLE
Library does not support IPv6 addresses (in server URLs)

### ISSUE THREAD

**Issue by rutgerbrf** [nats-io/nats.rs#185]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)

nats.rs commit a79367581e
NATS Server version 2.2.2

#### rustc version (`rustc --version` - we support Rust 1.41 and up)

rustc 1.52.1 (9bc8c42bb 2021-05-09)

#### OS/Container environment:

Manjaro 21.0.5 Ornara

#### Steps or code to reproduce the issue:

1. Start a NATS server (on localhost)
2. Run the 'nats-box' example, like this:
    `cargo run --example nats-box -- --server '[::]:4222' sub test`
    (or like this: `cargo run --example nats-box -- --server '[::]' sub test`)

#### Expected result:

```
Listening on 'test'
```

#### Actual result:

```
Error: failed to lookup address information: Name or service not known
```

#### Notes:

It seems like this line of code is at fault (though a bit more code is involved): https://github.com/nats-io/nats.rs/blob/a79367581e44b5504bba054d2f9994f672410f46/src/connector.rs#L411
I would not expect a server URL/address like `::` to work, only `[::]` (I guess these technically aren't URLs, but `localhost:4222` works).

**Comment by spacejam** [comment]
Hey @rutgerbrf , thank you for opening this issue. I've added additional parsing logic for ipv6 [here](https://github.com/nats-io/nats.rs/pull/189), and I believe it should work with your use case. I'll cut a new version shortly that includes the change.

**Comment by spacejam** [comment]
Version 0.9.19 has been published which includes this update. Please feel free to open another issue if you hit any more friction! Thanks again for reporting this.
