### ISSUE TITLE
Provide a way to enable TCP_NODELAY on the underlying stream

### ISSUE THREAD

**Issue by vmalloc** [nats-io/nats.rs#186]
#### Use Case:
In many latency-sensitive uses, having TCP NODELAY set to true can greatly reduce latencies and unexpected connection lags.
#### Proposed Change:

When connecting to NATS, in the `connect_addr` function, add something along the lines of:

```rust
 let (underlying, _) = stream.get_ref();
 underlying.set_nodelay(true)?;
```

Since the server side for NATS is in Go, its default is NODELAY as it is, so the only side needing this fix is the client side.

Thanks in advance!

**Comment by derekcollison** [comment]
I thought it was that way, all clients are.. @spacejam ?

**Comment by spacejam** [comment]
https://github.com/nats-io/nats.rs/blob/5ec9f5df94427b7ae9240afd15752d25f8e4a1b8/src/connector.rs#L235
