### ISSUE TITLE
Add non-blocking consumer process methods / Possibility to perform a straight call to the Stream

### ISSUE THREAD

**Issue by rguarnotta** [nats-io/nats.rs#188]
#### Use Case:

Ability to request the last message(s) from a given stream and consumer instead of waiting indefinitely for a message  to arrive (currently handled by the `process` method). It would be nice to be able to create a new method to allow for direct call to the stream to get the last message or last X messages. A method that does not depend on publisher's delivery rates.

#### Proposed Change:

A method that is similar to the the `Subscription`'s `try_next` method but returning the latest message(s) from the `Stream` instead of returning `None` in the absence of a new message. 

#### Use Case Example

```rust
use env_logger::Env;
use log::info;
use nats::jetstream::{AckPolicy, ConsumerConfig, DeliverPolicy, NextRequest, StreamConfig};
use std::str;
use std::thread;
use std::time::Duration;

fn main() {
    env_logger::Builder::from_env(Env::default().default_filter_or("info")).init();
    let nc = nats::connect("localhost::4222").unwrap();
    let _ = nc.delete_stream("test_stream");

    // Create a new stream.
    nc.create_stream(StreamConfig {
        name: "test_stream".to_string(),
        subjects: Some(vec!["101-meter".to_string(), "102-meter".to_string()]),
        ..Default::default()
    })
    .unwrap();

    // Create a consumer with options.
    let consumer_1_opts = ConsumerConfig {
        durable_name: Some("test_consumer_1".to_string()),
        filter_subject: Some("101-meter".to_string()),
        deliver_policy: DeliverPolicy::Last,
        ..Default::default()
    };

    let mut consumer_1 = nc.create_consumer("test_stream", consumer_1_opts).unwrap();
    
    // Start loop.
    loop {
        // Blocking method as it waits for a new message to arrive. 
        // Ideally replaced that returns the latest data regardless if a new message has arrived. 
        let latest_data = consumer_1
            .process(|msg_1| {
                println!(
                    "Consumer 1 got message on {} - data is: {:?}",
                    &msg_1.subject,
                    str::from_utf8(&msg_1.clone().data)
                );
                Ok(msg_1.data.to_vec())
            })
            .unwrap();

        // Do something with latest data. 


        info!("tick");
        thread::sleep(Duration::from_millis(500));
    }
}
```

**Comment by rguarnotta** [comment]
@derekcollison @spacejam : could you please provide me a quick status update on this feature request? Does it make sense and is there a plan to add it to the code base? 

Thanks for your active development of this crate, great tool.

**Comment by spacejam** [comment]
Hey @rguarnotta, one issue is that the idea of processing the same message multiple times by the same consumer is a bit of a model mismatch with jetstream consumers. However, you can get the desired behavior that you want right now by creating a lighter weight "ephemeral" consumer each time around the loop, setting `durable_name` to `None`:

```rust
loop {
    let mut consumer_1 = nc
        .create_consumer(
            "test_stream",
            ConsumerConfig {
                durable_name: None,
                deliver_subject: Some("test_consumer_1".to_string()),
                deliver_policy: DeliverPolicy::Last,
                filter_subject: Some("101-meter".to_string()),
                ..Default::default()
            },
        )
    
    let latest_data = consumer_1
            .process(|msg_1| {
                println!(
                    "Consumer 1 got message on {} - data is: {:?}",
                    &msg_1.subject,
                    str::from_utf8(&msg_1.clone().data)
                );
                Ok(msg_1.data.to_vec())
            })
            .unwrap();

        // Do something with latest data. 


        info!("tick");
        thread::sleep(Duration::from_millis(500));
}
```

Since it seems like you're only doing this at 2hz, it seems like latency isn't much of a concern while getting the last message. Does the above example solve your need?

**Comment by rguarnotta** [comment]
Thank you @spacejam. I'll give it a try and let you know if that works!

**Comment by Jarema** [comment]
@rguarnotta The JetStream API was reworked. 
I'm closing this issue as the examples are irrelevant now.
Feel encouraged to test the new API and create a new issue if you find that you don't have what you need.
