### ISSUE TITLE
support retaination for queue supscription

### ISSUE THREAD

**Issue by abdelmonem17** [nats-io/nats.rs#193]
Hello every one.
Is there a way to support TTL in nats messaging ?

Thank you in advance.

**Comment by derekcollison** [comment]
Can you help us understand a bit more what you mean here? Thx.

**Comment by abdelmonem17** [comment]
@derekcollison  for example if I have a subscriber in a topic so if one publish a message in this topic but the the subscriber not available in this time but we be available after some time so I want this subscriber to recieved the privious published messages

**Comment by derekcollison** [comment]
That is JetStream and the rust client has a first rev at support. @spacejam can highlight more info.

**Comment by abdelmonem17** [comment]
@derekcollison I want something in nats like in rabbitmq ttl [rabbitmq ttl](https://www.rabbitmq.com/ttl.html)

**Comment by derekcollison** [comment]
Understood, JetStream is a superset for the most part of what is possible with RMQ and yes we support MaxAge per message.
You need to compile JetStream in optionally in the rust client but everything you need should be there.

**Comment by abdelmonem17** [comment]
@derekcollison thank you for help regarding to jetSteam is there is a support for   [NATS Streaming](https://docs.nats.io/nats-streaming-concepts/intro) ?

**Comment by derekcollison** [comment]
No, STAN is being sunset.

**Comment by abdelmonem17** [comment]
@derekcollison  so jetStream is the sutable alternative?

**Comment by derekcollison** [comment]
Yes JetStream is the future direction for materialized persistence in NATS.

**Comment by abdelmonem17** [comment]
@derekcollison could you provide an example for using jstream as queue WorkQueue and have a retention police as I tried and have errors or provide me with an informative documentation to do that?

**Comment by derekcollison** [comment]
@spacejam Should be able to, but if not I can figure it out.

**Comment by abdelmonem17** [comment]
@derekcollison  @spacejam thank you for your help but is there any update regarding to using jstream as queue WorkQueue and have a retention police?

**Comment by derekcollison** [comment]
As I mentioned, JetStream supports that, and I believe the Rust client does support all of the JetStream patterns except the new order consumer that we just landed in the Go client. So this should be possible today. /cc @spacejam

**Comment by abdelmonem17** [comment]
@derekcollison  could you help me and try it or provide me with a documentation for JetStream to do that?

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats.rs/blob/main/tests/jetstream.rs#L56

**Comment by abdelmonem17** [comment]
@derekcollison thank you for your help but sorry you create test2 and use it in all case which is not a queue group please check here [queue group](https://docs.nats.io/nats-streaming-concepts/channels/subscriptions/queue-group)  and when I try to do so i have an error 

>  Custom { kind: Other, error: "multiple non-filtered consumers not allowed on workqueue stream" }

the code 
```
 nc.create_stream(StreamConfig {
        name: "test2".to_string(),
        retention: RetentionPolicy::WorkQueue,
        ..Default::default()
    }).unwrap();

   // nc.create_stream("test2")?;
    nc.stream_info("test2")?;
    nc.create_consumer("test2", "consumer1")?;

    let consumer2_cfg = ConsumerConfig {
        durable_name: Some("consumer2".to_string()),
        ack_policy: AckPolicy::Explicit,
        deliver_subject: Some("consumer2_ds".to_string()),
        ..Default::default()
    };
    nc.create_consumer("test2", &consumer2_cfg).unwrap();
```

**Comment by derekcollison** [comment]
Make the consumer a pull consumer (no deliver subject) and you can run as many apps as you want that will pull from the workqueue. 
We will make some efforts to improve the docs and the JetStream examples, hopefully @spacejam can do some of this work this week.

**Comment by abdelmonem17** [comment]
I tried this and same error could you try to that ?

**Comment by derekcollison** [comment]
@spacejam can give it a try, I am tied up with other things.

**Comment by spacejam** [comment]
@abdelmonem17 the following work queue code works for me: https://github.com/nats-io/nats.rs/pull/202

Please open a separate issue if you have remaining concerns.
