### ISSUE TITLE
Add missing stream config options

### ISSUE THREAD

**Issue by cortopy** [nats-io/nats.rs#198]
#### Use Case:

`StreamConfig` doesn't have an option for:

- `max-msgs-per-subject`
- `ack` to acknowledge publishes (I'm not sure if this is the same as the `no_ack` field already available)

#### Proposed Change:

Add the missing fields

#### Who Benefits From The Change(s)?

Anybody who uses the rust client to create streams

#### Alternative Approaches

Use the cli instead of rust to create streams

**Comment by spacejam** [comment]
`StreamConfig::max_msgs` and `Message::ack` / `Message::ack_kind` have been available since March 8th with the release of version 0.9.5.

**Comment by cortopy** [comment]
@spacejam but `max_msgs` is not the same as `max-msgs-per-subject` in the cli is it? 

In the cli there is `max-msgs` and then `max-msgs-per-subject`

**Comment by spacejam** [comment]
@cortopy ahh right, I've added that one here: https://github.com/nats-io/nats.rs/pull/201 and it may be published later today if the pending reviews can get through

`ack` is represented already as `no_ack`.
