### ISSUE TITLE
Subscription with_handler is easy to drop

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nats.rs#2]
I have seen this and others reported as well. If you do not capture a subscriber from a call such as

```rust
nc.subscribe("help.request")?.with_handler(move |m| {
    m.respond("ans=42")?; Ok(())
});
```
The subscription will be dropped immediately and no messages will be received.

We could return an io::Result to have the compiler complain that the return result is not being handled, etc.

Or maybe look to have the subscription lifetime tied to the callback thread?

**Comment by spacejam** [comment]
Here's one possible way to deal with it:

Since the closure is running in a new thread, you can have a bool on `Subscriber` that flips on when `with_handler` is called. In `Drop` for `Subscriber`, don't call `unsub` if the bool is flipped on, but clone `subs` and `writer` and pass them into the new thread, and have the thread unsubscribe when iteration terminates.

Is it a bug to have multiple handlers? Each call to `with_handler` spins up a new thread that receives from the same channel, splitting work across threads. If multiple consumer threads are legal, change the bool to an `Arc<AtomicUsize>` and keep a running count that gets incremented on each call to `with_handler` and decremented when its loop ends. (to make it single-panic proof, write your own Dropper type that gets called when the Arc hits 0, which has a copy of the `subs` and `writer` `Arc<Mutex<...>` types).

**Comment by derekcollison** [comment]
Thanks, was thinking something similar.

**Comment by derekcollison** [comment]
I want with_handler to return a different type that does not allow iteration etc and probably does not allow another call to with_handler since that is a bit confusing. Would rather see code that grabs a message and puts it in another thread or async task etc.

**Comment by dwaynebradley** [comment]
So, you would prefer folks to use the pattern of:

1. "Multiple Subscriptions with 1 handler each" vs.
2. "1 Subscription with multiple handlers" (like you have now)

for processing the same message multiple times in their code, right?

If you do prefer 1 above, is having the `with_handler` function on the `Subscription` really what you want? It seems a little strange to have that called out in a function and not be able to call it multiple times especially returning `Self`. If you want to force only having a single handler per subscription, would it be better to just have the handler called out as a 2nd parameter in the `subscribe` function?

**Comment by derekcollison** [comment]
The default I think folks should use is the iterator pattern. But several folks pushed for the handler, but this should be optional so I did a chain which seems idiomatic. However as @spacejam pointed out it can be called multiple times. And what happens is a load balanced processing of the message stream, which is not bad but is not obvious IMO and the handler should be the same.

So my thought is to make it only callable once, and if you want to scale out you can use threads or tasks for use with async runtimes (I will do an example of this too).

I will also make a subscription with a handler require a call to `close()` to drop the subscription interest. Meaning the code you and I got caught up with will work properly after this change.

**Comment by derekcollison** [comment]
Please take a look.

https://github.com/nats-io/nats.rs/pull/3

**Comment by derekcollison** [comment]
This was fixed with #3

**Comment by nazar-pc** [comment]
Well, now I had to write this hack to make sure I do not have random subscriptions floating with already dropped handlers so they can't be stopped...:
```rust
struct SubscriptionHandlerWithUnsubscribe(Option<SubscriptionHandler>);

impl Deref for SubscriptionHandlerWithUnsubscribe {
    type Target = SubscriptionHandler;

    fn deref(&self) -> &Self::Target {
        self.0.as_ref().unwrap()
    }
}

impl Drop for SubscriptionHandlerWithUnsubscribe {
    fn drop(&mut self) {
        self.0.take().unwrap().unsubscribe().unwrap();
    }
}
```

**Comment by derekcollison** [comment]
The original code did drop, but myself and others had the following issue, we expected the code below to work but it didn't.

```rust
fn main() -> std::io::Result<()> {
  let nc = nats::connect("demo.nats.io")?;
  nc.subscribe("bar")?.with_handler(move |msg| {
     println!("Received {}", &msg);
     Ok(())
   });
   Ok(())
}
```

You can always create a normal subscription and turn into an iter yourself inside of a thread or task.

Also, I would expect the above to work but would also understand if I wanted to unsubscribe before the connection went out of scope or the program ended I would need to hold onto the sub itself.

**Comment by nazar-pc** [comment]
What about this?:
```rust
fn main() -> std::io::Result<()> {
  let nc = nats::connect("demo.nats.io")?;
  let _ = nc.subscribe("bar")?.with_handler(move |msg| {
     println!("Received {}", &msg);
     Ok(())
   });
   Ok(())
}
```

I think it is quite common pattern with `MutexGuard` for instance.

**Comment by derekcollison** [comment]
I am still new to Rust, so this may be incorrect, but if you want compiler support for forcing one to deal with a return it would need to be a Result. Which we could also consider such that the example I gave above would not compile (at least cleanly) since I was not handling the Result. But of course that would mean a `?` or `.unwrap()` or `.expect()` to be in place as well.

**Comment by nazar-pc** [comment]
Result is not required, you can use https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute and compiler will generate a warning for you

**Comment by derekcollison** [comment]
Good to know!

I still like being able to write like the example above, most subscriptions like that will live for the length of the connection itself and I don't need to capture the sub, so the `let _ = ` feels superfluous.

**Comment by nazar-pc** [comment]
Having full control over subscription lifecycle and getting warnings feels more idiomatic. It is really awkward to unsubscribe otherwise as you have seen. Also wrappers for one-time subscriptions (for single message) would simplify things in my case, this is essentially what I do at the end.

**Comment by derekcollison** [comment]
One time messages are mostly a result of a `request()` and for that we have a single option.

Again if you want to control the sub you have to capture the variable, so this feels natural. Wherever in your code you need to `unsubscribe()` you need to have the sub itself ;)
