### ISSUE TITLE
Subscriptions and consumers should implement Iterator/Stream

### ISSUE THREAD

**Issue by glueball** [nats-io/nats.rs#214]
#### Use Case:

I think the use case that benefits more of this change is the (not unusual) case that the application opens the subscription at startup and keep them open for the whole time. 

Short-lived subscriptions/consumers can also benefit, either by using a timeout or the `.take()` method.

#### Proposed Change:

To make the crate much more idiomatic, subscriptions and jetstream consumers should implement the Iterator trait (sync version) and Stream (async version).  That trait could be implemented directly in the subscription/consumer, or they could implement IntoIter/IntoStream traits to convert them into Iterators/Streams. 

#### Who Benefits From The Change(s)?

All crate uses can potentially benefit. This change would make the crate more idiomatic, and allow users to leverage all the iterator/stream machinery in the standard lib and other crates.

#### Alternative Approaches

Don't do it.

**Comment by spacejam** [comment]
Stream will be added for the async subscriber once it lands in the standard library. Subscription already implements `IntoIterator` - the trait that enables usage in Rust `for` loops.
