### ISSUE TITLE
Publish to jetstream with ack

### ISSUE THREAD

**Issue by Jarema** [nats-io/nats.rs#215]
#### Use Case:
Hopefully I didn't missed that, but I don't see an option for having ack from jetstream when publishing messages.
That should be in place to fully utilize jetstreams.

#### Proposed Change:
Have a Publish implementation in nats::jetstream module That sends request to jetstream subject and process the response.

#### Who Benefits From The Change(s)?
Everybody using jetstream.

#### Alternative Approaches
Publish without waiting for ack.

**Comment by Jarema** [comment]
@spacejam are there any plans to implement this soon? If not, I can work on this, though it might take some time due to me adopting Rust and having also other responsibilities.

**Comment by glueball** [comment]
You can use `.request` instead of `.publish`. It will block until jetstream ACKs the message. Use `.request_timeout` if you want to set a timeout.

**Comment by derekcollison** [comment]
We need to implement this if not already, @spacejam will chime in shortly.

**Comment by Jarema** [comment]
I allowed myself to create PR (being beginner rustician).

Is this the right approach?
