### ISSUE TITLE
JS Consumer lost after disconnect/reconnect

### ISSUE THREAD

**Issue by glueball** [nats-io/nats.rs#224]
#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
0.15.2

#### OS/Container environment:
Docker version 20.10.8, build 3967b7d
Official Nats image.

```
[1] 2021/09/18 17:47:42.919585 [INF] Starting nats-server
[1] 2021/09/18 17:47:42.919630 [INF]   Version:  2.4.0
[1] 2021/09/18 17:47:42.919634 [INF]   Git:      [e49eb66]
```

#### Steps or code to reproduce the issue:

Consider this code

"Pull" version
```rust
use nats::jetstream::Consumer;
use nats::Options;

fn disconnected() {
    println!("NATS Disconnected!");
}

fn reconnected() {
    println!("NATS Reconnected!");
}

fn main() {
    let nats = Options::default()
        .disconnect_callback(disconnected)
        .reconnect_callback(reconnected)
        .connect("localhost:4222")
        .unwrap();

    let mut consumer = Consumer::create_or_open(nats, "test-stream", "my-consumer").unwrap();

    loop {
        let message = consumer.pull();

        println!("Got message: {:?}", message);

        if let Ok(msg) = message {
            msg.ack();
        }
    }
}
```

"Process" version
Change the loop to the following (the rest is just the same):

```rust
    loop {
        consumer.process(|message| -> std::io::Result<()> {
            println!("Got message: {:?}", message);
            Ok(())
        });
    }
```

1. Open nats server
2. With the CLI, create a stream named "test-stream" for subjects "test.>"
3. Execute client.
4. With the CLI, send messages to appropriate subjects (I use "test.me")
5. Close nats server
6. Re-open nats server

#### Expected result:

The client still receives stream messages after the re-connect.

As a higher level methor, `process` should continue to block (until the reconnection attempts are exhausted, at least).

As a low level method, `poll` could do the same, or maybe just return some `Err` upon disconnection and let application code decide what to do (btw, using io::Error is not very ergonomic, would be better to have a Nats specific error type, but that's another issue).

#### Actual result:

No more messages are received after the re-connect.

```
Got message: Message { subject: "test.me", headers: None, reply: Some("$JS.ACK.test-stream.my-consumer.1.30.30.1631988049016713000.0"), length: 2 }
Got message: Message { subject: "test.me", headers: None, reply: Some("$JS.ACK.test-stream.my-consumer.1.31.31.1631988050514986200.0"), length: 2 }
NATS Disconnected!
NATS Reconnected!
```

```
93cd05d6a9c9:~# nats -s nats consumer info test-stream my-consumer 
Information for Consumer test-stream > my-consumer created 2021-09-18T17:32:34Z

Configuration:

        Durable Name: my-consumer
           Pull Mode: true
         Deliver All: true
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 20,000
   Max Waiting Pulls: 512

State:

   Last Delivered Message: Consumer sequence: 31 Stream sequence: 31
     Acknowledgment floor: Consumer sequence: 31 Stream sequence: 31
         Outstanding Acks: 0 out of maximum 20000
     Redelivered Messages: 0
     Unprocessed Messages: 3
            Waiting Pulls: 0 of maximum 512
```

If I restart the rust program, the "lost" messages are delivered.

Note that I tested a regular subscription, and it works just right:

```rust
    let sub = nats.subscribe("test.me").unwrap();

    for message in sub {
        println!("Got message: {:?}", message);
    }
```
```
Got message: Message { subject: "test.me", headers: None, reply: None, length: 2 }
Got message: Message { subject: "test.me", headers: None, reply: None, length: 2 }
NATS Disconnected!
NATS Reconnected!
Got message: Message { subject: "test.me", headers: None, reply: None, length: 2 }
Got message: Message { subject: "test.me", headers: None, reply: None, length: 2 }
```

**Comment by Jarema** [comment]
I'm afraid there is a bigger issue there: if client disconnects while app using nats.rs is runing, all publish attemps still return Ok().

```
fn publ(nc: Connection) {
    let mut i = 0;
    loop {
        i = i+1;
        match nc.publish("test.asdf", format!("{}", i)) {
            Ok(m) => println!("ok from {}: {:?}", i, m),
            Err(e) => println!("error from {}:{}", i, e),
        };
        thread::sleep(Duration::from_millis(1000));
    }
}
```

if you run this code and after few publishes, restart the nats server, it will still log `ok`, even during server downtime.

If thats the case, then Jetstream methods will block, as Jetstream is basically request-response patterns. Publish to dead server will block, as subscription on `reply` topic will never get the message.

**Comment by Jarema** [comment]
I was able to replicate it with request/response pattern (which is used by jetstream consumers). This seems logical - there is quite a chance that you will kill the server before it sent the response to already published request. Request would never get the response on `inbox` subject. In case of js, that request should be retried after reconnect (we could have some basic exponential bacoff mechanism with timeouting requiests, or even reacting to disconnect event).

**Comment by caspervonb** [comment]
Closing this out as this API no longer exists on main.
