### ISSUE TITLE
Remove `client` and `double_acked` from `Message`

### ISSUE THREAD

**Issue by MattesWhite** [nats-io/nats.rs#227]
#### Use Case:
In my unit test I want to create a `Message` to test my subscriber code.
   - Currently, this is not possible as the API does not allow to create an own message.

#### Proposed Change:
Remove the `client` and `double_acked` fields from `nats::Message`. 
The client is only used for the respond method this could be changed to:
```rust
impl Message {
    pub fn respond(&self, connection: &Connection, response: Message) -> Result<()> { ... }
}
```
`double_acked` can be part of a `jetstream::Message` that wraps `Message`. I think a separation of both messages shouldn't be to hard.

Once, users can build their own messages some of `Connection`'s methods could be simplified. For example, `Connection::publish()` could investigate the contents of `Message` and act accordingly. As a result, `Connection::publish_with_reply_or_headers()` could be removed.

#### Who Benefits From The Change(s)?
1. Users who want to test their consumer side code.
1. By separation of concerns the code base will become easier to read and maintain.
1. ~Performance: The message payload is mostly passed by `impl AsRef<[u8]>`. When a `Vec` is created for the payload it is passed as `&Vec` to a method like `publish()` which in turn copies the whole payload again by creating and allocating a `Vec` from `&[u8]`. This is a double allocation which can cost a lot of performance. By directly constructing a `Message` and passing the ownership, allocations can be reduced and performance increases.~
   Looking closer into the code base, it turns out I was wrong ... sry

#### Alternative Approaches
Offer a function to create mock messages for unit testing.

**Comment by Jarema** [comment]
Just a note: ‘respond’ itself is used in ack related ‘nats::Message’ methods. Nonetheless, ale seem to be referenced only in jetstream context.

**Comment by Jarema** [comment]
Another note: I was considering using enum instead of `nats::Message` utilizing https://tokio.rs/tokio/tutorial/framing pattern for #228 .

That could be used for MSG, HMSG, NO RESPONDERS (or ERRS if there are more server side error message responses now/in future). Jetstream message could be part of it, though it's different layer of abstraction.

**Comment by MattesWhite** [comment]
To be honest I haven't used JetStreams, yet, so I can't talk much about it. But as the framing pattern suggests it is a good thing to separate the data send on the TCP stream and the higher-level organization. However, (without knowing the protocol specifically) for me it seems that JetStream is a rather distinct protocol from the usual NATS stuff as it provides way more/powerful features. Accordingly, I would still argue for a separation of the _normal_ NATS message and JetStream messages.

**Comment by Jarema** [comment]
Reopening, as we decided to think through the solution once more.

**Comment by Jarema** [comment]
done in #258 

`Message` now has `Client` as an `Option` which allows users to create instances.
`Message::new()` was also added for convenient use.
