### ISSUE TITLE
Request timeout broken in 0.16

### ISSUE THREAD

**Issue by JamesSmith2** [nats-io/nats.rs#268]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included below version and environment information
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)

nats = 0.16 - NOK
nats = 0.15 - OK

#### rustc version (`rustc --version` - we support Rust 1.41 and up)

rustc 1.56.1 (59eed8a2a 2021-11-01)

#### OS/Container environment:

Windows 10

#### Steps or code to reproduce the issue:

`nc .request_timeout("license", data, Duration::from_secs(20)).await`

#### Expected result:

Should wait 20s

#### Actual result:

100ms only

**Comment by Jarema** [comment]
Thank you for taking time in submitting the issue.

I was not able to replicate it though.
Could you please check the error message from the `request_timeout`?
I'm suspecting, that you might get `no_responders` error that was added in `0.16.0` which errors immediately if server finds out that there are no subscribers for a subject you send request to.

**Comment by JamesSmith2** [comment]
Hello,

yes seems that you are correct, i tested it with no responders as i wanted it to fail, but only after 20s not before.

**Comment by Jarema** [comment]
If you want to test longer timeouts for some reasons and not get hit by `no responders`, you can first subscribe to the subject you're sending request to, then send request with timeout.

```Rust
let _sub = nc.subscribe("events").unwrap();
let resp = nc.request_timeout("events", "test", Duration::from_seconds(10))
```

It would fail as no-one send the response, but it would wait for timeout, as there is actually a `responder`.

**Comment by JamesSmith2** [comment]
Thank you for the help.
