### ISSUE TITLE
jetstream_kv::Watch and jetstream_object::Watch conflict v0.17.0

### ISSUE THREAD

**Issue by mvniekerk** [nats-io/nats.rs#272]
- [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
Git git+ssh://git@github.com/nats-io/nats.rs.git?branch=release-v0.17.0#6a5359cd955b73c30a70366dc9449968716c901c
v0.17.0

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.57.0 (f1edd0429 2021-11-29)

#### OS/Container environment:
Ubuntu 20.04

#### Steps or code to reproduce the issue:
```rust
use nats::jetstream::Watch;
```

#### Expected result:
Any way to get to the KV subscription Watch type 

#### Actual result:
There's more than one Watch type exported

**Comment by Jarema** [comment]
Once again - thanks for your early tests on feature branch.

I addressed it differently: with reorganizing kv and object_store modules.

https://github.com/nats-io/nats.rs/pull/275

**Comment by mvniekerk** [comment]
@Jarema I had a look at your PR, much cleaner than my quick-fix PR. 👍
