### ISSUE TITLE
failure to connect with TLS and RSA private key

### ISSUE THREAD

**Issue by baadc0de** [nats-io/nats.rs#277]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
```
name = "async-nats"
version = "0.10.1"
```

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
`rustc 1.59.0-nightly (0fb1c371d 2021-12-06)`

#### OS/Container environment:
macOS Monterey, v.12.1

#### Steps or code to reproduce the issue:
Create a CA, private key and certificate using RSA as the algorithm. Using the `nats` utility from nats-box docker image, the certificates are interpreted correctly and the utility connects to the NATS server. Rust client failes (see below for details).

The CSRs have been generated following this tutorial: https://developers.cloudflare.com/cloudflare-one/identity/devices/mutual-tls-authentication

CA
```
{
  "CN": "REDACTED",
  "key": {
    "algo": "rsa",
    "size": 4096
  },
  "names": [
    {
      "C": "SI",
      "O": "REDACTED"
    }
  ]
}
```

and CSR for client:

```
{
  "CN": "REDACTED",
  "hosts": [
    ""
  ],
  "key": {
    "algo": "rsa",
    "size": 4096
  },
  "names": [
  ]
}
```

Using in the client with

```rust
let connection = async_nats::Options::new()
            .tls_required(true)
            .add_root_certificate("../nats/ca.pem")
            .client_cert("../nats/cert.pem", "../nats/cert-key.pem")
            .connect("tls://REDACTED:4222")
            .await
            .expect("NATS connection");
```

#### Expected result:
NATS client connects successfully

#### Actual result:
NATS client fails with 
`NATS connection: Custom { kind: InvalidData, error: "no keys found in the client key file" }`

The culprit seems to be [src/auth_utils.rs:161](https://github.com/nats-io/nats.rs/blob/48653119d9a03022870e41f443c463983732cbc8/src/auth_utils.rs#L161) where it's scanning for `-----BEGIN PRIVATE KEY-----` while the RSA cert has `-----BEGIN RSA PRIVATE KEY-----`.

**Comment by baadc0de** [comment]
With further research, `cfssl` can also produce PEM files with `BEGIN EC PRIVATE KEY` so maybe the parsing should be more robust and accept any files that have `BEGIN ... PRIVATE KEY`.

There is a workaround, openssl can be used to convert the cfssl generated key to a format that nats.rs expects:
```
openssl pkey -in cert-key.pem -out cert-key-vanilla.pem
```

This emits a PEM file that uses `BEGIN PRIVATE KEY`. Simply editing PEM file to remove the algorithm name corrupts it, so this conversion command is apparently necessary.

It's up to the maintainer to decide whether to tweak the parsing code, maybe add a documentation note or something else.

**Comment by Jarema** [comment]
Thanks for the report.

I think we should be able to delegate whole work around reading and checking PEM files to `rustls`, so we could avoid expecting specific start/end marks and not hardcode them in NATS client.

**Comment by baadc0de** [comment]
I agree, depending on https://github.com/rustls/pemfile sounds like a better idea. There is a test file in it that covers my use https://github.com/rustls/pemfile/blob/109b643e2b72ceee11e8601580fa386bef851945/tests/data/zen2.pem

**Comment by mvniekerk** [comment]
This also comes into play when you're using certmanager on Kubernetes deployments where you don't have a quick `openssl pkey -- what what` to do this for you
