### ISSUE TITLE
possible panic in JetStream Object.read

### ISSUE THREAD

**Issue by stevelr** [nats-io/nats.rs#279]
If I'm reading this correctly, the two occurrences of `cmp::max` should be replaced with `cmp::min`. If more bytes are read from `self.remaining_bytes` than fit in `buffer`, this would panic.
https://github.com/nats-io/nats.rs/blob/3af59b5ed6051d2f3fc28bc773e3c4515fbae4e7/src/object_store.rs#L284-L299

You might not have encountered this bug in testing if the read buffer is always larger than the message size.

Also a question - what is the purpose of `skip_next`?

**Comment by Jarema** [comment]
Thanks for the report.

We were testing such cases, but our tests were not properly filling test data. 

Will report back after fixing that.

**Comment by stevelr** [comment]
PR 279 closed and replaced with https://github.com/nats-io/nats.rs/pull/282

**Comment by caspervonb** [comment]
Good catch!
Closing this out as resolved by #282.
