### ISSUE TITLE
Watch hangs when run in Tokio

### ISSUE THREAD

**Issue by mvniekerk** [nats-io/nats.rs#285]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
0.17

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
1.57

#### OS/Container environment:
Ubuntu 20.04

#### Steps or code to reproduce the issue:
https://github.com/mvniekerk/nats-rs-kv-example

Test: mpsc_tokio_hang_thread_bucket_0
#### Expected result:
Doesn't hang and produces results

#### Actual result:
Hangs

**Comment by Jarema** [comment]
@mvniekerk  I ckecked your examples and it seems to be a lot of abstraction on NATS crate.

Nonetheless - The values are being retrieved in a loop of `mpsc_tokio_hang_thread_bucket_0` (you can check it by printing them) and the `watch` works properly. It's just that there are some runtime tasks that are blocking.

To quote the docs: 
```dropping a Runtime will wait indefinitely for all tasks to terminate, and there are cases where a long blocking task has been spawned, which can block dropping Runtime.```

You can check that with `rt.shutdown_background()`, but of course that's not a solution for your tokio code, just to prove the point :).

**Comment by Jarema** [comment]
@mvniekerk can we close this?

**Comment by Jarema** [comment]
I'm closing this, as this is not library issue.

Thanks again for helping us testing unreleased unstable features!
