### ISSUE TITLE
KV Watch panics with None unwrap

### ISSUE THREAD

**Issue by mvniekerk** [nats-io/nats.rs#286]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
0.17.0

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
1.57
#### OS/Container environment:
Ubuntu 20.04
#### Steps or code to reproduce the issue:
https://github.com/mvniekerk/nats-rs-kv-example
Test get_values_bucket_1

#### Expected result:
Produces values

#### Actual result:
Segfaults

**Comment by Jarema** [comment]
Fixed with #286 

Closing.

**Comment by mvniekerk** [comment]
@Jarema Thanks man, just a check are these changes on the v0.17 branch yet?
