### ISSUE TITLE
explicit TLS config from rustls

### ISSUE THREAD

**Issue by tarasmatsyk** [nats-io/nats.rs#294]
#### Use Case:
I am trying to configure TLS on the client and found a rustls re-export a bit confusing. I am pretty new to Rust and may* miss the point here. What puzzles me is that I cannot use [rustls](https://github.com/rustls/rustls) directly. As it's a [dependency](https://github.com/nats-io/nats.rs/blob/9f324f96c955b044a5a53d3471c6e8d2823d29a6/Cargo.toml#L49) I am wondering why it was decided to wrap it inside crate rather than accept it's structures as parameters. At the moment it's quite interesting as it forces user to add `natsrc::` to every rustls type used.

Perhaps it's a somewhat version lock in which I am missing here, not sure.

#### Proposed Change:
Is it possible to migrate from crate declaration [crate::rustls::ClientConfig:options.rs#L41](https://github.com/nats-io/nats.rs/blob/d22329cdd9daa7965ed62caa224a0e745e292f5e/src/options.rs#L41) to use:
```
use rustls::ClientConfig
```
I am happy to help with transition if it sounds ok

#### Who Benefits From The Change(s)?
That should help avoid type mismatch confusion and provide nats.rs with rustls updates. TLS libs are patched quite often 

<img width="748" alt="Screenshot 2022-01-08 at 19 59 10" src="https://user-images.githubusercontent.com/4949627/148654658-da7aef48-3901-4840-b497-bfe088b47954.png">

#### Alternative Approaches
Not sure there is 😄, type alias?

**Comment by Jarema** [comment]
Thanks for filing the issue!

Quoting the docs:
```
To avoid version conflicts, the rustls version used by this crate is exported as nats::rustls.
```

so yes, this is related to incompatibility.
Most users use `client_cert()` option.

As we're calling `rustls` methods internally, not binding to a specific version would break.

Is there a reason why not just add `use nats::rustls`?

Then you could simply write `let tls_config = rustls::ClientConfig::new()`?

NOTE: there are breaking changes between 0.19 and 0.20 and we're still at 0.19.

**Comment by tarasmatsyk** [comment]
I see, that makes sense now :) 
🤦 should have read documentation more carefully. 

Yeah, 0.20 seem to have enough updates to keep people busy. 

`client_cert` is not really an option for me as I pem files are read way before execution gets to nats session. I have raw binaries and would need to come up with some sort of virtual path. 

Thank you for clarification Tomasz, should I close the issue?

**Comment by Jarema** [comment]
If it's clear, I'm closing it  🙂 

Have a good day.
