### ISSUE TITLE
PushSubscription::unsubscribe also drains

### ISSUE THREAD

**Issue by stevelr** [nats-io/nats.rs#297]
According to the documentation for PushSubscription::unsubscribe, it's supposed to do less than ::drain:

> Unsubscribe a subscription immediately without draining.
    /// Use `drain` instead if you want any pending messages
    /// to be processed by a handler, if one is configured.

But the implementations for `unsubscribe` and `drain` are exactly the same

**Comment by Jarema** [comment]
Thanks for submitting the issue.

We have to look into all `unsubscribe` methods and make sure they're aligned.
