### ISSUE TITLE
Threads are not stopped on drop/close()

### ISSUE THREAD

**Issue by ShellWowza** [nats-io/nats.rs#300]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)

0.16.0

#### rustc version (`rustc --version` - we support Rust 1.41 and up)

rustc 1.57.0 (f1edd0429 2021-11-29)

#### OS/Container environment:

Ubuntu 20.04.3 LTS

#### Steps or code to reproduce the issue:

Available at https://github.com/ShellWowza/nats-testcase

#### Expected result:

When the Connection is either dropped or closed, all NATS threads are joined on before the return from close() or the Drop implementation, so that the slog logger held by the reconnect/disconnect callback is dropped and therefore flushes at the end of main().

#### Actual result:

NATS threads are not stopped immediately on close() or Drop, resulting in a thread holding onto the logger via a reconnect/disconnect callback past the point where main() returns, which means it does not flush - not all 200-odd lines buffered in the logger are printed.

**Comment by Jarema** [comment]
Thanks for filling up the issue. I will check that.
