### ISSUE TITLE
Use time crate instead of chrono

### ISSUE THREAD

**Issue by ShellWowza** [nats-io/nats.rs#308]
#### Use Case:

The chrono crate is unmaintained and has a [known security flaw](https://rustsec.org/advisories/RUSTSEC-2020-0159) (albeit one not triggered by nats.rs), requiring whitelisting in security tools like `cargo audit`. Changing to use the time crate would avoid this needed whitelisting.

#### Proposed Change:

Use the time crate in place of chrono. This does require a breaking API change.

#### Who Benefits From The Change(s)?

Users who use tools such as `cargo audit` to check their dependency chains for known security issues.

#### Alternative Approaches

Stay as is and document prominently that the security flaw does not affect nats.rs.

#### Notes

I have a patch available for this. Would copyright assignment or similar need to happen?

**Comment by Jarema** [comment]
Thanks for catching this @ShellWowza!

Agree on swapping chrono crate in favour of time.

Feel free to issue a PR. That's all we need to proceed.

**Comment by caspervonb** [comment]
We'd also need to support time crate in serde_nanos.
