### ISSUE TITLE
Struct `PullSubscription` is private

### ISSUE THREAD

**Issue by k-u-s** [nats-io/nats.rs#311]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ x] Included below version and environment information
 - [ x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
nats = "0.17"

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.57.0 (f1edd0429 2021-11-29)

#### OS/Container environment:
podman: version 3.4.2
image tag:  nats:2.7

#### Steps or code to reproduce the issue:
Trying to use PullSubscription struct fails to compile

```rs

use nats::jetstream::PullSubscription;
fn main() {}

```

#### Expected result:
struct is public

#### Actual result:
struct is private

**Comment by k-u-s** [comment]
Created pr for it: https://github.com/nats-io/nats.rs/pull/312

**Comment by Jarema** [comment]
@k-u-s thanks for filling out this issue! 
I created another PR #313 as your fix surfaced some issues with the docs.
Cherry-picked your first commit to credit your contribution 🙂
