### ISSUE TITLE
Fails to parse IPv6 URL with credentials and port

### ISSUE THREAD

**Issue by gaffneyc** [nats-io/nats.rs#322]
I ran into this issue while trying to use Vector to connect to a NATS server in a hosted environment. I don't have any experience with Rust but I was able to track it down to this library. The example I was able to get compiled uses `nats` but Vector uses `async_nats`.

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)

```
0.18.1
```

#### rustc version (`rustc --version` - we support Rust 1.41 and up)

```
rustc 1.58.1 (gentoo)
```

#### OS/Container environment:

Gentoo Linux

#### Steps or code to reproduce the issue:

```rust
// docker run --rm -ti -p 4223:4223 nats -p 4223 --user user --pass pass
fn main() {
    let nc = nats::connect("nats://user:pass@[::1]:4223");
    println!("{:#?}", nc);
}
```

#### Expected result:

The client would connect to `::1` with credentials set.

#### Actual result:

```
Err(
    Custom {
        kind: Uncategorized,
        error: "failed to lookup address information: Name or service not known",
    },
)
```

Originally tested against 0.10.1 gave the below error. It appears that the parsing code which returned the error has since been removed.

```


Err(
    Custom {
        kind: InvalidInput,
        error: "unable to parse port number in URL: nats://user:pass@[fdaa::3]:4223. If you are trying to use ipv6, please wrap the address in square brackets: [nats://user:pass@[::1]:4223] etc... with an optional colon and port after the closing bracket.",
    },
)
```

**Comment by Jarema** [comment]
Thanks for filling the issue.

That is very old dependency.
Vector should update their dependency.
Probably it's best to wait some time until our refactor of async codebase.

**Comment by gaffneyc** [comment]
Oh interesting! I some how thought 0.10.1 was the latest release and tested against that (again, I have absolutely zero experience with Rust).

I've updated to the latest version of nats.rs (0.18.0) for a local test and now I'm getting a different error. I'm running NATS in a Docker container and trying to connect to it via IPv6 localhost (::1). It works just fine if I connect to the IPv4 address or if I use a domain name that only resolves to an IPv6 IP (e.g. `::1 localhost-ipv6` in /etc/hosts).

Setup
```
docker run --rm -ti -p 4223:4223 nats -p 4223 --user user --pass pass
```

```rust
fn main() {
    let nc = nats::connect("nats://user:pass@[::1]:4223");
    println!("{:#?}", nc);
}
```

```
Err(
    Custom {
        kind: Uncategorized,
        error: "failed to lookup address information: Name or service not known",
    },
)
```

**Comment by jszwedko** [comment]
This still seems to be an issue in 0.19.0. I opened https://github.com/nats-io/nats.rs/pull/386 to address it.
