### ISSUE TITLE
Run test against more than one version of the server

### ISSUE THREAD

**Issue by Jarema** [nats-io/nats.rs#328]
#### Use Case:
There are some difference in behaviour in both server and client. It would be good to test against few version to go not only through newest server path.
#### Proposed Change:
Run GHA tests against at least. newest and 2.6 nats server.
#### Who Benefits From The Change(s)?
Users of older versions of the server would get their codebase paths tested.
#### Alternative Approaches
Accept lower test coverage for older server versions. (not a good idea).

**Comment by caspervonb** [comment]
Go get doesn't make it easy to distinguish between HEAD and latest tag as far as I can tell? otherwise we can just add it to the test matrix trivially.
