### ISSUE TITLE
Make nats::subscription::IntoIter public

### ISSUE THREAD

**Issue by lkral-navmatix** [nats-io/nats.rs#329]
#### Use Case:
I believe it is currently not possible to store `blocking::Unblock<nats::subscription::IntoIter>` in a struct as `IntoIter` is not exported publicly. Boxing in this case can't be used as `blocking::Unblock` would not implement `Stream`. 

#### Proposed Change:
Make `nats::subscription::IntoIter` publicly accessible.

#### Who Benefits From The Change(s)?
Anybody that would like to store return type of `blocking::Unblock::new(subscription.into_iter())` in a struct for later use.

#### Alternative Approaches
I am not currently aware of different approach to solve this

**Comment by caspervonb** [comment]
We should resolve the Voldemort types.
However, we've been working on a real async crate: published as async-nats where subscribers are streams. Still early but, it is a lot more performant than the asynk wrapper.

**Comment by caspervonb** [comment]
Closing as stale.
