### ISSUE TITLE
`Connection` does not properly dispose of all allocated memory

### ISSUE THREAD

**Issue by lkral-navmatix** [nats-io/nats.rs#341]
- [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
version = "0.18.1"
#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.57.0 (f1edd0429 2021-11-29)
#### OS/Container environment:
WSL on Windows 10 and Linux (Ubuntu 20.04)
#### Steps or code to reproduce the issue:
```
loop {
        let _nats_connection = match nats::Options::new().connect("nats://localhost:4222") {
            Ok(x) => x,
            Err(err) => {
                return;
            }
        };
    }
```
#### Expected result:
Once the `Connection` is dropped, I'd expect that the associated memory is freed.
#### Actual result:
Applications using this library allocate memory every time `Connection` is created, but at least some of that memory remains allocated for the entire life of the application, even after the `Connection` is dropped (NATS `8222/connz` confirms that the connection is disconnected as well). 
This was first observed in multiple applications using this library which create/drop `Connection` for certain logical units over time. This happens regardless of NATS connection duration (tested up to several days).
Note that the allocations do not seem linear, in the MCVE the application eventually start allocating memory at seemingly faster rate and after running for several minutes it gets into the GiB range. This occurs in the more complex applications as well although it takes longer to manifest due to lower rate of creating new `Connection`.

**Comment by lkral-navmatix** [comment]
Not very familiar with memory debugging in Rust, but Valgrind Massif seems to indicate that vast majority of the allocated memory that is not being freed was created in `nats::client::Buffer::new`.

**Comment by Jarema** [comment]
Thanks for the report. I'm looking into it.

**Comment by Jarema** [comment]
@lkral-navmatix after a debugging session:

What is happening is if you just drop the connection, the `shutdown` is called which only triggers the shutdown process of the connection and does not wait for it. That leads to some floating threads for some time and if you have a high enough rate of new connections, the memory usage and number of threads will grow. After some time, the memory will be released as the thread numbers will decline.

To avoid that situation, you can simply call `close()` on the connection:


```
loop {
        let _nats_connection = match nats::Options::new().connect("nats://localhost:4222") {
            Ok(x) => x.close(),
            Err(err) => {
                return;
            }
        };
    }
```

We deliberately did not wait for the graceful shutdown of the connection while just dropping as that _can_ introduce unexpected delays while getting out of scope.

Let me know if calling `close` fixes the problem for you.

**Comment by lkral-navmatix** [comment]
@Jarema I assume these extra threads should close fairly quickly, right? The two applications that are currently experiencing this issue did not deallocate the memory even after hours of running while no new `Connection` were created.

I will modify the application to explicitly call `close` and see if I can replicate the issue again.

**Comment by lkral-navmatix** [comment]
Using `close` seems to make the thread count work as expected (without it the count is all over the place but eventually comes down) and it increases/decreases by 2 for each `Connection` created/closed. 

Unfortunately this does not seem to be the root cause of the memory allocations.

If I make the application create about 160 `Connection`, then close them few minutes later, the memory stays allocated. If I keep repeating this process, the application keeps allocating new memory every time which eventually leads to it running out of memory.

As the previously allocated memory does not seem to be reused, it seems like it is either still referenced somewhere, or I am running into some issue with memory fragmentation.
