### ISSUE TITLE
Hide nats::asynk behind a feature flag

### ISSUE THREAD

**Issue by jaskij** [nats-io/nats.rs#375]
And probably make the feature optional.

This way, an unnecessary dependency is not pulled in if the user does not want it.

**Comment by Jarema** [comment]
With the new async client, we don't put much effort into sync client, and soon a wrapper will be available.

If youre keen on continue using sync client, feel free to contribute with that feature.

**Comment by jaskij** [comment]
No, not really. The async client works better with my code, and with it's rapid progress since I created this issue I see no issue with moving to it completely.
