### ISSUE TITLE
unsub code looks wrong

### ISSUE THREAD

**Issue by nazar-pc** [nats-io/nats.rs#4]
First of all, this (and similar code for `close` function):
https://github.com/nats-io/nats.rs/blob/b5576cfee5edc3687975356d5c9f2e1ad248bbfc/src/lib.rs#L655-L658
Looks suspicious after looking at what `.unsub()` does:
https://github.com/nats-io/nats.rs/blob/b5576cfee5edc3687975356d5c9f2e1ad248bbfc/src/lib.rs#L585-L592

The property `.unsub` is immediately flipped back.

Second, the only place where `.unsub` property was checked seems to be incorrect too:
https://github.com/nats-io/nats.rs/blob/b5576cfee5edc3687975356d5c9f2e1ad248bbfc/src/lib.rs#L625-L634

I have a feeling that it should have been `if !self.unsub`, or better yet, don't use `.unsub` and name it `.subscribed` with the opposite meaning, then `if self.subscribed` would be easy and natural to read.

I would be able to make a PR, but I'm not 100% I understood it correctly.

P.S. I'd not mutate that property from the outside at all if possible, maybe consider moving different structs into different files, at least to a degree, to add more boundaries and make API cleaner.

**Comment by derekcollison** [comment]
Thanks for the feedback. Will take a closer look. My goal was to not have subscriptions with a handler attached unsubscribe when being dropped from scope like normal subscriptions do.

**Comment by derekcollison** [comment]
It does what its supposed to but agree can make it clearer..

**Comment by nazar-pc** [comment]
Hm... can you explain a bit more, please? I don't understand why `.unsub` is set to `true` right before it is set to `false` unconditionally in `.unsub()` function. There is either piece of logic missing or it is just unnecessary or something else.

**Comment by derekcollison** [comment]
When you attach a handler we do not want the subscription with the server to be dropped when the local object is dropped so we prevent the unsub protocol from being sent.

https://github.com/nats-io/nats.rs/blob/b5576cfee5edc3687975356d5c9f2e1ad248bbfc/src/lib.rs#L572

That way this works

```rust
nc.subscribe("foo").with_handler( some_func() )
```

Meaning messages will still be delivered to the handler even though the subscription struct itself will be dropped since it is not captured.

**Comment by nazar-pc** [comment]
I got it, but why is it set to `true` in `SubscriptionHandler` right before calling `self.sub.unsub()` then?

**Comment by derekcollison** [comment]
Because `unsubscribe()` or `close()` are legit ways  of removing interest, so when they are called I want the underlying unsub when the enclosed Subscription gets dropped to send the UNSUB protocol to the server.

**Comment by nazar-pc** [comment]
But right after assigning `true` it is instantly reassigned to `false` in `unsub()` function implementation:
https://github.com/nats-io/nats.rs/blob/b5576cfee5edc3687975356d5c9f2e1ad248bbfc/src/lib.rs#L585-L586
Is that a typo?

**Comment by derekcollison** [comment]
No that prevents it from executing twice in the upper levels.

**Comment by nazar-pc** [comment]
Unless I'm missing something last 2 comments do not make any sense together.
We essentially execute following instructions:
```
self.unsub = true;
self.unsub = false;
...
```

Those are fully completely synchronous calls in the same thread.

Hence the original question: why assigning `true` if it doesn't impact anything?

**Comment by derekcollison** [comment]
You are correct, I used to check the boolean in the `unsub()` call but I lifted it to the `drop()`. Will clean it up, thanks.

**Comment by derekcollison** [comment]
If that looks ok feel free to close.

**Comment by nazar-pc** [comment]
Looks good, thanks!
