### ISSUE TITLE
Possible memory leak on high messages throughput with v0.20.1

### ISSUE THREAD

**Issue by mikhailantoshkin** [nats-io/nats.rs#451]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
`version = "0.20.1"`

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
`rustc 1.59.0 (9d1b2106e 2022-02-23)`

#### OS/Container environment:
`Linux 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

#### Steps or code to reproduce the issue:
First discovered as a weird memory usage in Vector using NATS source described in this [issue](https://github.com/vectordotdev/vector/issues/12834)

When running this code and hitting NATS with ~800k msg/sec memory usage shoots up and after all messages are processed memory is not being reclaimed by the system

Reciever
```
use nats;
use std::error::Error;
use tokio;
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let nc = nats::asynk::connect("172.10.0.1:4222").await?;
    let sub = nc.subscribe("msg.test").await?;

    // Receive a message.
    while let Some(msg) = sub.next().await {
        println!("{:#?}", msg)
    }
    Ok(())
}
```

Producer snipet
```
    let nc = nats::connect("172.10.0.1:4222").unwrap();
    loop {
        nc.publish("msg.test", MSG).unwrap();
    }
```

nats-top output
![image](https://user-images.githubusercontent.com/51194616/170193488-547c00b4-f889-47cb-84cb-a0acee578c24.png)

Memory usage
![image](https://user-images.githubusercontent.com/51194616/170193636-624006b3-a40f-4cba-a40b-735b15b1b3dd.png)
![image](https://user-images.githubusercontent.com/51194616/170193887-6c22cf52-81f3-4f8c-b5e3-6169ecf0393f.png)

#### Expected result:
After all messages has been processed memory is reclaimed by the system

#### Actual result:
Memory leak

If there is anything else I can provide for further clarification - please let me know

Thanks

**Comment by Jarema** [comment]
@mikhailantoshkin  thanks for the report.
I'm looking into this.

**Comment by Jarema** [comment]
@mikhailantoshkin

Which side encounters the leak?
The receiving end?

**Comment by mikhailantoshkin** [comment]
@Jarema yes, I'm not sure what causes it, but until some threshold memory usage is not increasing at all, but then it skyrockets

**Comment by mikhailantoshkin** [comment]
Here is some example screenshots from setup I'm using to reproduce this
![image](https://user-images.githubusercontent.com/51194616/170537866-c07c626c-c576-4f8f-80cb-bc1dd3bfd015.png)
![image](https://user-images.githubusercontent.com/51194616/170538199-5c9b1acf-c62c-4e58-9b7a-9a0c379abcbf.png)

**Comment by mikhailantoshkin** [comment]
I created a [repo](https://github.com/mikhailantoshkin/nats-leak) with my test setup to reproduce the issue

**Comment by mikhailantoshkin** [comment]
Decided to retest it with version `0.23.0` and also run it under [bytehound](https://github.com/koute/bytehound). Weirdly enough, it does not reproduce when running `nats-eater` binary from demo repo with bytehound, but running it standalone still reproduces the memory leak. 

Anyway, here is the [link](https://drive.google.com/file/d/1Y6l69NKzQlu3VRFHWhYI4SkgFX-vlndE/view?usp=sharing) for the profiling report (452 Mb uncompressed)

Also, it does not reproduce with `async-nats` `0.19.0`, though it is slower according to nats-top

**Comment by stevelr** [comment]
In your loop where you are using sleep() to try to achieve a certain message rate per second, the sleep time is increased by the  async-nats client's default flush interval, so you are guaranteed (with default settings) to get a lower bandwidth than the target from the cli parameter.

One change that will increase bandwidth with async-nats is to call flush() after publish. For performance reasons, the default flush interval (time it waits to see if there are more messages to send before flushing on its own) is non-zero. The nats team is planning to do some performance tuning of the default interval but for unique situations like this benchmark you probably want non-default values anyway.

There are still two issues in this benchmark that interfere with the two goals of getting a specific target message rate and getting great throughout. To increase accuracy, you could use Interval to measure elapsed time and sleep the difference between desired interval and elapsed. To increase throughput, publish messages in batches of N, followed by one call to flush per batch, and increase the expected interval by a factor of N. That will let you amortize overhead of rust thread switching and take advantage of TCP and network efficiencies. I might try N=100, or N=1000 if the messages are very small. 

Also, `println!()` may become a bottleneck so you might want to print only every N as well.

**Comment by Jarema** [comment]
As this is an issue for deprecated sync client, and vector already moved to `async-nats` (which is also a lot faster now), I'm closing this issue.
