### ISSUE TITLE
Support async_std through feature flags

### ISSUE THREAD

**Issue by caspervonb** [nats-io/nats.rs#476]
#### Use Case:

Support either async-std or tokio executors without taking a dependency on the other one.

#### Proposed Change:

Use feature flags to take a dependency on either async-std or tokio runtime specific things.
Use future crate for everything that is not runtime dependent.

#### Who Benefits From The Change(s)?

Users of nats who already depend on async-std.

#### Alternative Approaches

Use tokio's compatibility features.

#### Prior Art

We had an attempt at this, but we're moving quickly making it pretty impossible to merge (https://github.com/nats-io/nats.rs/pull/398).

**Comment by Jarema** [comment]
As the `tokio` runtime became practically the default for async rust ecosystem, I'm closing this one.
