### ISSUE TITLE
Docs help: note the need for connection flush()

### ISSUE THREAD

**Issue by dontlaugh** [nats-io/nats.rs#48]
I was playing with this library, with a subscriber and a publisher program adapted from the readme, and I noticed my program was exiting before the underlying messages were sent.

```rust
    let conn = nats::connect(&server)?;
    if let Some(matches) = matches.subcommand_matches("pub") {
        let topic = matches.value_of("topic").unwrap();
        let rest = matches.value_of("values").unwrap();
        conn.publish(topic, rest)?;
        conn.flush();   // <---- this fixed it
    };
    if let Some(matches) = matches.subcommand_matches("sub") {
        let topic = matches.value_of("topic").unwrap();
        let sub = conn.subscribe(topic)?;
        while let Some(ms) = sub.next() {
            let s = String::from_utf8(ms.data)?;
            println!("sub: {}", s);
        }
    };
// exit
```

Not sure the best way to present in the README, but it was a little paper cut for me, so I'm noting it here.

**Comment by derekcollison** [comment]
Thanks, the messages should be flushed before the connection is closed when going out of scope.

**Comment by spacejam** [comment]
@dontlaugh I believe this should be addressed on master, as flush is called on drop

**Comment by dontlaugh** [comment]
@spacejam Master totally works, thank you. I'll roll with this for the time being.

```toml
natsio = {git = "https://github.com/nats-io/nats.rs", branch = "master"}
```

**Comment by spacejam** [comment]
This has been released (we moved crate names from natsio to nats)
