### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nats.rs#5]
Need to decide on which tech to use and whether or not we make this a feature flag.

Contenders are:

1. [native-tls](https://crates.io/crates/native-tls)
2. [openssl](https://crates.io/crates/openssl)
3. [rustls](https://crates.io/crates/rustls)

Any thoughts and comments welcome.

**Comment by derekcollison** [comment]
Interested in any feedback from @spacejam or @stjepang

**Comment by dwaynebradley** [comment]
One thing that I ran into previously with using the `openssl` crate was if I wanted to compile to a static binary, I had so switch to using `x86_64-unknown-linux-musl` for my target. I'm not sure if it is still that way or not though. I'm also not sure if `native-tls` or `rustls` forces doing the same either as I have not tried either of those at this point.

**Comment by derekcollison** [comment]
I think native-tls will use openssl on some platforms so I would imagine it does so. Rustls looks interesting and is all rust code, but also looks like the most work for sure.
