### ISSUE TITLE
Small API suggestions

### ISSUE THREAD

**Issue by stjepang** [nats-io/nats.rs#50]
Rename `ConnectionOptions`:
- Go and Java clients call it `Options`. I like that.
- Standard library has `OpenOptions` - note it's not named `FileOptions` because it's about the "open" action rather than the "file" result. In our case, the action is "connect" and the result of the action is "connection".
- Not a big deal, but I think `ConnectOptions` or `Options` would be a bit more idiomatic.

Don't re-export `native-tls`:
- Its API is not amazing to use and is not stable like Go's `tls` is.
- By re-exporting `native-tls`, we're bound to its versioning policy - if it bumps its major version number and we want to upgrade, then we have to bump our version number, too. 
- Other crates typically provide a subset of its features.
- Check out how `warp` handles TLS with its [`TlsServer`](https://docs.rs/warp/0.2.2/warp/struct.TlsServer.html) type. Here's an [example](https://github.com/seanmonstar/warp/blob/a6fcf76d43e0b3a11f445aacf638094e7dcd008b/examples/tls.rs).
- I suggest simply adding connect options like `cert_path()` and `key_path()` and we're done.

Don't export `ServerInfo`:
- It's just an internally used type.
- Other clients don't export it.

**Comment by derekcollison** [comment]
I like all of these..

**Comment by spacejam** [comment]
+1 for all of these

**Comment by stjepang** [comment]
Another inconsistency I noticed - `ConnectionOptions` has the following methods:

- `fn reconnect_buffer_size()`
- `fn tls_required()`
- `fn set_disconnect_callback()`

It seems to me that the "set_" prefix is redundant. So why not the following?

- `fn reconnect_buffer_size()`
- `fn tls_required()`
- `fn disconnect_callback()`
