### ISSUE TITLE
how to subscribe history message

### ISSUE THREAD

**Issue by zyc801208** [nats-io/nats.rs#54]
When nats client crash, and then it reconnect to nats server, and resubscribe topic. 
My problem is, will the nats client  lost message produced between crash time.
And how to use the durable feature for nats-streaming server?

**Comment by derekcollison** [comment]
If your client crashes there is no durability. JetStream works with plain NATS protocol and can work with the NATS Rust client.

See here for more info.

https://github.com/nats-io/jetstream

**Comment by zyc801208** [comment]
Thank you very much for replying my problem immediately.   
Jetstream is cool, I saw some document.

About natsio(https://docs.rs/natsio/0.3.2/nats/struct.Connection.html#method.subscribe), I still have some problem below:
> pub fn subscribe(&self, subject: &str) -> Result<Subscription>  

The above method allow me to subscribe a subject,  if I want to subscribe a subject maybe published an hour ago, may I  do that?  
Or will you add a time field on subscribe method?

And will the subject message be drop if no-one subscribe it?

**Comment by derekcollison** [comment]
To receive messages from JetStream you will not subscribe directly, you need to create a consumer. We will add in helpers eventually to the client to do this in Rust.

If you want to do that today, you can create a pull based consumer with the jsm utility in the jetstream repo and then your rust application will send a request for each message.

If you want a push based consumer, you can create a durable consumer with a delivery subject, again using the jsm tool to do so for now. That delivery subject will be the one you subscribe to in your application.

Not the ack policy on the push based consumer, if the message you receive in your app has a reply subject on it you need to respond to that.

**Comment by zyc801208** [comment]
Thanks a lot, I'll try JetStream.

**Comment by phuoc-thanh** [comment]
Hi @derekcollison ,

Just wondering if there are any plan to support durable subscription (stan client) in next releases?

**Comment by derekcollison** [comment]
No plans for STAN support for this client. We will support JetStream of course and you can actually interoperate with JetStream with the existing client already.
