### ISSUE TITLE
Does `webpki-roots` copyleft license impact the license of program using `nats.rs`?

### ISSUE THREAD

**Issue by turbinenreiter** [nats-io/nats.rs#552]
Using `cargo deny` we stumbled over the license of `webpki-roots` and were wondering how that impacts the licensing four our own work.

`webpki-roots = "0.22"`
https://github.com/nats-io/nats.rs/blob/50e33cf39f7f65f771160511811ae4bcf730acf2/async-nats/Cargo.toml#L33

**Comment by Jarema** [comment]
@turbinenreiter thanks for catching thos one.

`webpki-roots` is MPL licensed.

https://github.com/rustls/rustls-native-certs is an alternative, with its pros and cons listed and licensed under:
- Apache License version 2.0.
- MIT license.
- ISC license.

@philpennock and suggestions and preferences from a security perspective? (look at https://github.com/rustls/rustls-native-certs#should-i-use-this-or-webpki-roots). Are we fine with switching to the alternative?

Even if MPL is fine (IANAL), would be better to have fewer licenses under our libraries.

**Comment by Jarema** [comment]
@turbinenreiter as we moved away from`webpki-roots`, issue has closed.
