### ISSUE TITLE
Async-nats has significantly higher latency compared to blocking client or golang client

### ISSUE THREAD

**Issue by ilya-zlobintsev** [nats-io/nats.rs#573]
#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)

0.17.0

#### rustc version (`rustc --version` - we support Rust 1.41 and up)

1.62.0

#### OS/Container environment:

Arch Linux

#### Steps or code to reproduce the issue:

I have made a crude latency test using async-nats:

```rust
use futures_util::StreamExt;
use std::time::{Duration, Instant};
use tokio::time::sleep;

#[tokio::main]
async fn main() {
    let client = async_nats::connect("localhost:4222").await.unwrap();
    let mut subscriber = client
        .subscribe("latency-testing".to_owned())
        .await
        .unwrap();

    for i in 0..100 {
        let published_at = Instant::now();

        client
            .publish("latency-testing".to_owned(), i.to_string().into())
            .await
            .unwrap();

        subscriber.next().await.unwrap();

        println!(
            "Latency between publish and consume: {}μs",
            published_at.elapsed().as_micros()
        );

        sleep(Duration::from_millis(200)).await;
    }
}
```
And the latencies I'm getting are both high on average and also inconsistent:
```
Latency between publish and consume: 340μs
Latency between publish and consume: 101475μs
Latency between publish and consume: 102369μs
Latency between publish and consume: 2063μs
Latency between publish and consume: 102596μs
Latency between publish and consume: 102535μs
Latency between publish and consume: 102454μs
Latency between publish and consume: 2362μs
Latency between publish and consume: 796μs
Latency between publish and consume: 1978μs
Latency between publish and consume: 101523μs
Latency between publish and consume: 101465μs
```

An identical example using the blocking version of the crate performs much better and with consistent latency:
```rust
use std::time::{Duration, Instant};
use tokio::time::sleep;

#[tokio::main]
async fn main() {
    let client = nats::connect("localhost:4222").unwrap();
    let subscriber = client.subscribe("latency-testing").unwrap();

    for i in 0..100 {
        let published_at = Instant::now();

        client.publish("latency-testing", &i.to_string()).unwrap();

        subscriber.next().unwrap();

        println!(
            "Latency between publish and consume: {}μs",
            published_at.elapsed().as_micros()
        );

        sleep(Duration::from_millis(200)).await;
    }
}
```
```
Latency between publish and consume: 668μs
Latency between publish and consume: 768μs
Latency between publish and consume: 630μs
Latency between publish and consume: 675μs
Latency between publish and consume: 701μs
Latency between publish and consume: 554μs
Latency between publish and consume: 698μs
```

The golang library has even lower latency:
```golang
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/nats-io/nats.go"
)

func main() {
	nc, err := nats.Connect(nats.DefaultURL)

	if err != nil {
		log.Fatalf("%v", err)
	}

	produced_at := time.Now()

	nc.Subscribe("latency-testing", func(msg *nats.Msg) {
		fmt.Printf("Latency between publish and consume: %vμs\n", time.Since(produced_at).Microseconds())
	})

	for i := 0; i < 100; i++ {
		produced_at = time.Now()

		data := []byte{byte(i)}
		nc.Publish("latency-testing", data)

		time.Sleep(time.Millisecond * 200)
	}
}
```
```
Latency between publish and consume: 302μs
Latency between publish and consume: 282μs
Latency between publish and consume: 149μs
Latency between publish and consume: 336μs
Latency between publish and consume: 207μs
Latency between publish and consume: 278μs
Latency between publish and consume: 351μs
Latency between publish and consume: 283μs
Latency between publish and consume: 266μs
Latency between publish and consume: 350μs
```

#### Expected result:

The latency is comparable 

#### Actual result:

Async-nats performs significantly worse

**Comment by Jarema** [comment]
Hey!

Thanks foe the report!
I assume it is related to unoptimized for latency flushing mechanism. Now it works well for big throughputs mostly.

We will optimise those soon, but meanwhile - can you call flush() immediately after publish() and let me know what are the results for you?

**Comment by ilya-zlobintsev** [comment]
> Hey!
> 
> Thanks foe the report! I assume it is related to unoptimized for latency flushing mechanism. Now it works well for big throughputs mostly.
> 
> We will optimise those soon, but meanwhile - can you call flush() immediately after publish() and let me know what are the results for you?

Yep, this does improve latency significantly, down to levels comparable with other clients:
```
Latency between publish and consume: 288μs
Latency between publish and consume: 856μs
Latency between publish and consume: 922μs
Latency between publish and consume: 672μs
Latency between publish and consume: 296μs
Latency between publish and consume: 337μs
Latency between publish and consume: 396μs
Latency between publish and consume: 345μs
Latency between publish and consume: 363μs
Latency between publish and consume: 499μs
Latency between publish and consume: 365μs
Latency between publish and consume: 481μs
Latency between publish and consume: 755μs
Latency between publish and consume: 827μs
```
Setting the flush interval to 1 millisecond also helps, but not as much as flushing manually:
```
Latency between publish and consume: 2294μs
Latency between publish and consume: 2503μs
Latency between publish and consume: 2612μs
Latency between publish and consume: 2400μs
Latency between publish and consume: 2658μs
Latency between publish and consume: 1528μs
Latency between publish and consume: 1549μs
````
It gets slightly lower (down to ~1ms) when setting the interval to a very low value (1 microsecond), thought I don't expect that to be a very good solution in terms of resource usage.

**Comment by esemeniuc** [comment]
More recent benchmark, latency is still roughly 5x the synchronous version

https://gist.github.com/esemeniuc/caf0bba5f87cc90c2e5a10bb9e554b11

**Comment by NorbertBodziony** [comment]
Any update on this. This really hurts our performance. Happy to contribute if somebody can point me what might be an issue.

**Comment by Jarema** [comment]
As this was discussed on NATS.io Slack, there is no "latency", rather a default flush interval bigger than in sync/go client.

In NATS messages are buffered before send to optimize throughput and performance.
NATS is async by design.

Until improvement over flusher is done (which will work the same, but with some optimizations for low-throughput traffic), it's enough to `client.flush()` after a call when you expect response for that publish.

For more context of your case, @NorbertBodziony , can you share example snippet that is hurt by this behaviour?

**Comment by NorbertBodziony** [comment]
Thanks for response @Jarema, by performance issue I meant case without `flush`. I assumed this is temporary hack since it is easy to forget to add this after each publish call.

**Comment by Jarema** [comment]
@NorbertBodziony, typically, you should not need to flush unless you wait for published message straight after publishing it, which does not sound like an often use case.

Can you share a snippet of code affected?

**Comment by NorbertBodziony** [comment]
@Jarema  Here is how we send msg via js.
```  pub async fn send_request(&self, user_id: u64, payload: UserRequest) {
    let bytes = utils::serialize_request(payload);
    self
      .js_client
      .publish(
        RE_USER_REQUEST_STREAM_NAME.to_string() + "." + &user_id.to_string(),
        Bytes::from(bytes),
      )
      .await
      .expect("Failed to send request");
  }
  ```
Then in another thread/machine we handle it with .
```  
pub async fn get_request_stream_by_risk_engine(
    &self,
  ) -> Pin<Box<impl futures::Stream<Item = (UserRequest, jetstream::Message)>>> {
    let name = "RISK_ENGINE";
    let stream = self
      .js_client
      .get_or_create_stream(utils::get_request_stream_config())
      .await
      .unwrap();
    let consumer = stream
      .get_or_create_consumer(
        name,
        PullConfig {
          durable_name: Some(name.to_string()),
          filter_subject: RE_USER_REQUEST_STREAM_NAME.to_string() + ".*",
          ..Default::default()
        },
      )
      .await
      .unwrap();
    let messages = consumer
      .messages()
      .await
      .expect("No messages found in stream");
    let new_stream = messages.then(|x| async move {
      let msg = x.expect("Invalid message");
      let request = utils::deserialize_request(msg.payload.clone());
      return (request, msg);
    });
    return Box::pin(new_stream);
  }
  ```
  Our usage requires resolving requests ASAP but also be able to handle high throughput of them.
  Anything above 10ms is too much. I got info from slack that attaching flush to all call will cause issues with throughput since we will be sending non-full packets.
  
  So here is my question, what would you suggest? Implementing some kind of flush in 5-10 ms intervals ?

**Comment by ilya-zlobintsev** [comment]
With 0.32.0 i am now getting consistently low latency (~160μs) in the original test.
