### ISSUE TITLE
Subscribing and reading a message

### ISSUE THREAD

**Issue by codecandy2015** [nats-io/nats.rs#58]
Hi,
I am very new to this nats client. I am trying to read a simple message via pub/sub. While compiling I get the error 
**method not found in `nats::Channel`**

My code looks like,
`
pub fn subscribe_nats(_tn: &String, _nc: &Client,) -> Result<(), Box<dyn std::error::Error>> {
  let sub = _nc.subscribe(_tn, None)?;
  while let Some(msg) = sub.next() {
            let s = String::from_utf8(msg.data)?;
            println!("sub: {}", s);
        }
  Ok(())
}
`

How do I get the messages from the Channel - is that the right way to do - your examples do not show me any other method
any help is appreciated
thanks
Candy

**Comment by derekcollison** [comment]
Start here: https://github.com/nats-io/nats.rs/blob/master/examples/nats-box/main.rs#L49

**Comment by codecandy2015** [comment]
Hi Derek,
Thanks for a quick reply. I was using a wrong lib. In you read me could you please add

[dependencies]
natsio = "*"

Loads of NATS Rust libs - makes it confusing.

Thank you.
Candy

**Comment by derekcollison** [comment]
We are moving to the official nats crate soon. /cc @spacejam
