### ISSUE TITLE
Ability to make client reconnect every second indefinitely

### ISSUE THREAD

**Issue by chris13524** [nats-io/nats.rs#581]
#### Use Case:

I like the reconnection capabilities of the sync nats client. You can set to keep reconnecting a max number of times (which can be None for infinity) and can also set a function to set the duration between reconnects (I would set to 1 second).

#### Proposed Change:

Support:

- https://github.com/nats-io/nats.rs/blob/main/nats/src/options.rs#L83
- https://github.com/nats-io/nats.rs/blob/main/nats/src/options.rs#L91

**Comment by Jarema** [comment]
Hey!

Thanks for the issue.

We will be adding configurable retry backoff very soon. That will allow you to configure it as requested.
