### ISSUE TITLE
Add flush parameter to publish

### ISSUE THREAD

**Issue by buffalu** [nats-io/nats.rs#582]
#### Use Case:
Add a flush parameter for low latency use cases that flushes automatically.

This is before and after flushing connection after every publish.
![image](https://user-images.githubusercontent.com/85544055/180868083-c119754f-20e4-4191-ac15-8244697d2a3a.png)

#### Proposed Change:
Add a parameter to automatically flush.

#### Who Benefits From The Change(s)?
Users trying to get low latency pubsub on NATS.

**Comment by Jarema** [comment]
Flushing after every publish can hurt throughput and put more load on the server too in some scenarios.

@buffalu We will be optimising flushing mechanisms after adding KV and ObjectStore (on which Im working right now).
Until then I suggest calling `client.flush()`.

**Comment by buffalu** [comment]
makes sense, i think it'd be helpful to add note somewhere as this was pretty surprising for us
