### ISSUE TITLE
async_nats::Error is not std::error::Error

### ISSUE THREAD

**Issue by jaskij** [nats-io/nats.rs#583]
Consider this sample:

```rust
    pub(crate) async fn new(
        nats_url: &str,
        subscription_type: EngineSubscriptionType,
    ) -> anyhow::Result<Receiver> {
        let client = async_nats::connect(nats_url).await?;
        let subscription = client
            .subscribe(Self::topic_from_subscription_type(&subscription_type))
            .await?;
        Ok(Receiver {
            client,
            subscription,
            subscription_type,
        })
    }
```

it will not compile, with an error:

```
error[E0277]: the size for values of type `dyn std::error::Error + Sync + std::marker::Send` cannot be known at compilation time
  --> src/tasks.rs:35:19
   |
35 |             .await?;
   |                   ^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `dyn std::error::Error + Sync + std::marker::Send`
   = note: required because of the requirements on the impl of `std::error::Error` for `Box<dyn std::error::Error + Sync + std::marker::Send>`
   = note: required because of the requirements on the impl of `From<Box<dyn std::error::Error + Sync + std::marker::Send>>` for `anyhow::Error`
   = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, Box<dyn std::error::Error + Sync + std::marker::Send>>>` for `Result<tasks::Receiver, anyhow::Error>`
```

There is a long-standing issue about this in Rust: https://github.com/rust-lang/rust/issues/60759

This actually stops me, as a user of this library, from easily forwarding the errors.

Outside of `async_nats::Error` changing to something different, the only workaround is writing a custom wrapper. I will experiment with using [`thiserror`](https://docs.rs/thiserror/latest/thiserror/), but don't expect success. My expectation right now to have to write the wrapper by hand.

**Comment by abalmos** [comment]
@jaskij I posted this issue in Slack last night and was just writing up the issue :) Thanks for getting to it before me!

You seem to be using anyhow. For now, you can replace `?` with `.map_err(|e| anyhow::anyhow!(e))?`

**Comment by jaskij** [comment]
@abalmos thanks for the workaround!

Here's a relevant `anyhow` issue: https://github.com/dtolnay/anyhow/issues/66

Generally, I'd expect library errors to be far more specific than either a `Box` or `anyhow::Error`. Sometimes, the library user will want to react differently depending on what the actual error is, and matching on an error `enum` is the easiest way to handle that. `thiserror` greatly simplifies writing such an error type, and deliberately does not appear in your API. I'm sure there are others, that's the one I use.

**Comment by Jarema** [comment]
Thanks for the report.

We are planning to move from boxed error to concrete errors as soon as kv/object store arrives, so pretty soon!

until then, I hope that the workaround is not too big issue.

**Comment by stevelr** [comment]
ping @Jarema - the precondition has been met
> We are planning to move from boxed error to concrete errors as soon as kv/object store arrives, so pretty soon!
Is this change on the way?

**Comment by Jarema** [comment]
@stevelr yes.
On it this week with intention to have it merged.

**Comment by Jarema** [comment]
All PRs for Core NATS and JetStreams has been already merged.
