### ISSUE TITLE
Can't treat authenticated and unauthenticated options builders as the same type

### ISSUE THREAD

**Issue by autodidaddict** [nats-io/nats.rs#59]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included below version and environment information
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### natsio version (`grep 'name = "natsio"' Cargo.lock -A 1`)

0.4.0

#### rustc version (`rustc --version` - we support Rust 1.37 and up)
1.43.1

#### OS/Container environment:

Ubuntu

#### Steps or code to reproduce the issue:

If I try and store the connection options builder in a variable, for example, to start building and then optionally add authentication if it's available, I can't use the authenticated and unauthenticated builders as the same variable, nor can I use them as branch arms.

This code works, but requires me to repeat the `connect` call inside the branch arm:

```
fn get_connection() -> nats::Connection {
    if let Some(creds) = get_credsfile() {
        nats::ConnectionOptions::new()
            .with_credentials(creds)
            .connect(&get_env(LATTICE_HOST_KEY, DEFAULT_LATTICE_HOST))
    } else {
        nats::ConnectionOptions::new().connect(&get_env(LATTICE_HOST_KEY, DEFAULT_LATTICE_HOST))
    }
    .unwrap()
}
```

what I'd like to be able to do is this (not currently possible)
```
fn get_connection() -> nats::Connection {
 let o = nats::ConnectionOptions::new();
  if let Some(creds) = get_credsfile() {
     o = o.with_credentials(creds);
  }
  o.connect(...).unwrap()
}
```

**Comment by autodidaddict** [comment]
The current builder pattern also blocks me from branching and using match arms for anonymous and authenticated connections:

```
    let nc = if let Some(creds) = get_credsfile() {
   |  __________________-
23 | |             nats::ConnectionOptions::with_credentials(creds)
   | |             ------------------------------------------------ expected because of this
24 | |         } else {
25 | |             nats::ConnectionOptions::new()
   | |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `nats::options_typestate::Authenticated`, found struct `nats::options_typestate::NoAuth`
26 | |         }

```

**Comment by autodidaddict** [comment]
this probably isn't a bug, just the builder not working the way I'd expect/hope

**Comment by derekcollison** [comment]
Once you auth you get a struct that you can not call additional auth methods on.

**Comment by stjepang** [comment]
@derekcollison Personally, I don't find the typestate pattern here all that useful in this case - it prevents bugs that are mostly theoretical (IMO) and benign, while making the API more cumbersome.

I suggest two solutions:

1. Just let users override a previously specified authentication method in the builder.
2. Move authentication as a first step in the builder.

In the second suggestion, we'd have the following constructors for `ConnectionOptions`:
- `ConnectionOptions::new()`
- `ConnectionOptions::with_token(token)`
- `ConnectionOptions::with_user_pass(user, pass)`
- `ConnectionOptions::with_credentials(path)`

This way we're still restricted to specify authentication only once, while `ConnectionOptions` is a single non-generic type.

@autodidaddict Do you have any preferences here?

**Comment by autodidaddict** [comment]
I like this. What is making my code forcibly awkward is that I can't build up a `ConnectionOptions` piece by piece as I get information from my own environment. The code should be able to look something like the following psuedocode:

```
let opts = ConnectionOptions::new();
if has_jwt { opts = opts.with_credentials(...) }
if has_tls { opts = opts.with_tls(...) }
if has_cert { opts = opts.do_cert_things(...) }
opts.connect()
```
What prevents this today is that at each step, there's a chance that the type returned is a different generic type,  so the compiler will tell me that the new value I'm setting for `opts` isn't of the right type.

my only solution now is to add more if statements and more redundant calls to functions that should be common (e.g. `connect`) 

I find that the typestate pattern often increases friction rather than decreases... and I don't care if it's there, as long as it doesn't force me to create unnecessary branches or duplication in my code.

**Comment by autodidaddict** [comment]
Here's code from the `nats-box` example right in the client repo:
```
    let nc = if let Some(creds_path) = args.creds {
        opts.with_credentials(creds_path).connect(&args.server)?
    } else {
        opts.connect(&args.server)?
    };
```
Note that `connect` has to be called in both branches because the data type of `opts` is different in each arm.

**Comment by derekcollison** [comment]
I like option #2 as well.

**Comment by spacejam** [comment]
https://github.com/nats-io/nats.rs/pull/60

**Comment by spacejam** [comment]
0.5.0 published with these changes
