### ISSUE TITLE
async client - 'nats: authorization violation' after connection loss

### ISSUE THREAD

**Issue by sebadob** [nats-io/nats.rs#591]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version

nats:2.8.4-alpine

#### rustc version

rustc 1.62.0

#### OS/Container environment:

Nats running on Kubernetes K3s

#### Steps or code to reproduce the issue:

Nats is using the *Embedded NATS Account Server Resolver* from the Helm Chart and was given an operator JWT and a linked system account. These were created with the `nsc` tool like described in the [Nats docs](https://docs.nats.io/using-nats/nats-tools/nsc).

I tried the connection with a `*.creds` file as well as with the extracted jwt and nkey seed like shown below.  
I have added some logs in the callbacks for debugging and to have some timeout in between the re-connects (not sure if this is the correct way to do it).

With a `*.creds` file, which is stored as a `String` in `config.nats_creds` in this case
```rust
    let nc = async_nats::ConnectOptions::with_credentials(&config.nats_creds)
    .expect("loading the 'nats.creds'")
    .disconnect_callback(|| async {
        error!("Nats disconnected - re-trying in 10 seconds");
        time::sleep(Duration::from_secs(10)).await;
    })
    .error_callback(|err| async move {
        error!("Nats connection error: {}", err);
        time::sleep(Duration::from_secs(10)).await;
    })
    .reconnect_callback(|| async {
        println!("reconnected to Nats");
    })
    .flush_interval(Duration::from_millis(100))
    .require_tls(true)
    .ping_interval(Duration::from_secs(30))
    .connect(&config.nats_url)
    .await
    .expect("nats connection");
    info!("New Nats connection established.");

    let js = jetstream::new(nc);
```

With the jwt and nkey seed extracted from the `*.creds* file:
```rust
    let seed = "the_extracted_seed";
    let key_pair = std::sync::Arc::new(nkeys::KeyPair::from_seed(seed).unwrap());
    let jwt = String::from("the_extracted_jwt");

    let nc = async_nats::ConnectOptions::with_jwt(jwt, move |nonce| {
        let mut key_pair = key_pair.clone();
        async move { key_pair.sign(&nonce).map_err(async_nats::AuthError::new) }
    })
    .disconnect_callback(|| async {
        error!("Nats disconnected - re-trying in 10 seconds");
        time::sleep(Duration::from_secs(10)).await;
    })
    .error_callback(|err| async move {
        error!("Nats connection error: {}", err);
        time::sleep(Duration::from_secs(10)).await;
    })
    .reconnect_callback(|| async {
        println!("reconnected to Nats");
    })
    .flush_interval(Duration::from_millis(100))
    .require_tls(true)
    .ping_interval(Duration::from_secs(30))
    .connect(&config.nats_url)
    .await
    .expect("nats connection");
    info!("New Nats connection established.");

    let js = jetstream::new(nc);
```

#### Expected result:

Both options work perfectly fine for establishing the connection, no matter if I just provide the `*.creds` file as a whole, or if I extract the jwt and nkey seed.

When the connection is being interrupted, it should just re-connect.

#### Actual result:

The problem comes up, when I lose the connection because of a network interruption. I have another Nats client running in a Java application. It just reconnects directly without any issues.  
When the interruption happens with the `async_nats` client though, the timeout between re-connects is working like expected, but I always get a `nats: authorization violation` from inside the 

```rust
.error_callback(|err| async move {
        error!("Nats connection error: {}", err);
        time::sleep(Duration::from_secs(10)).await;
    })
```

The log output then looks like this:

```
[2022-08-04T07:23:00Z ERROR signal_service::nats] Nats connection error: nats: authorization violation
[2022-08-04T07:23:10Z ERROR signal_service::nats] Nats disconnected - re-trying in 10 seconds
reconnected to Nats
[2022-08-04T07:23:20Z ERROR signal_service::nats] Nats connection error: nats: authorization violation
[2022-08-04T07:23:30Z ERROR signal_service::nats] Nats disconnected - re-trying in 10 seconds
reconnected to Nats
[2022-08-04T07:23:40Z ERROR signal_service::nats] Nats connection error: nats: authorization violation
[2022-08-04T07:23:50Z ERROR signal_service::nats] Nats disconnected - re-trying in 10 seconds
reconnected to Nats
```

The reconnects happen in a never ending loop and it never succeeds, even it should.  
The only way of getting back a connection is to kill the application (or maybe somehow drop the connection inside the async callback and re-create it) and restart it. Then I kill and restart, it connects directly without any issues.

Now the question:  
Am I doing something wrong here, or is this really a bug?  
I already tried different ways of providing the creds and jwt / seed, like static constants or even hardcoded values for testing. It is always the same result.

**Comment by Jarema** [comment]
Thanks for the report!

We're aware of this issue and actively working on it here:
https://github.com/nats-io/nats.rs/pull/578

Should be merged soon.

**Comment by sebadob** [comment]
Thank you very much.

**Comment by Jarema** [comment]
#578 has been merged.

Closing.

Expect a release soon!
