### ISSUE TITLE
missing timeout for TcpStream::connect in async-nats

### ISSUE THREAD

**Issue by thed0ct0r** [nats-io/nats.rs#601]
while testing the connection resiliency of the async-nats (v0.18.0) client, i encountered an issue where a the call to TcpStream::connect in src/connector.rs will hang (almost) indefinitely.
in 2 cases it took over 5 minutes for the connection to abort, and in  it took over 30 minutes to abort and reconnect.

i first encountered the issue while restarting a 3 server cluster in docker swarm, but have since managed to recreate it by scaling the amount of pods to 0 and some other scenarios (including using a proxy server for an external cluster).

this was relatively easily fixed by adding a public connection_timeout (with a default of 4 seconds) field to the ConnectOptions struct, and then changing the line: 
`let tcp_stream = TcpStream::connect(socket_addr).await?;`
to:
```
let tcp_stream = tokio::time::timeout(connection_timeout, TcpStream::connect(socket_addr))
            .await
            .map_err(|err| io::Error::new(ErrorKind::TimedOut, "connection: timeout elapsed with no server response"))??;
```

this greatly increases, imho, the resiliency of the connector and handles (gracefully) a whole host of issues that can occur in cloud environments (at least in my experience).

i would be happy to submit this as a pull request if it is something you are willing to accept.

**Comment by Jarema** [comment]
Hey.

We definitely want to improve the resilience of the connection.

Proposed solution looks good and we would happily become contribution!

**Comment by thed0ct0r** [comment]
Great, really appreciate it.
i'll get it cleaned up and add some documentation and testing. i'll submit it tomorrow.
