### ISSUE TITLE
Async NATS client does not support inbox prefix (and should)

### ISSUE THREAD

**Issue by autodidaddict** [nats-io/nats.rs#602]
From the documentation in a number of places, it states that NATS clients support the ability to define an inbox prefix:

```
However, as a client, there is the option of defining an explicit inbox prefix other than _INBOX.
```
But when looking at the async nats library, there is no way to generate an inbox with a prefix of anything other than `_INBOX`, which you can see here: https://docs.rs/async-nats/latest/src/async_nats/client.rs.html#193

I would like to be able to have a function in the client builder like `inbox_prefix()` that, when used, sets an alternate prefix other than `_INBOX`. There's no real workaround to this because the request functions use `new_inbox()` internally.

**Comment by Jarema** [comment]
Thanks for filling the issue!

We will consider what's the best way to allow for custom inboxes and implement a proper solution.
