### ISSUE TITLE
KV store blocks on calls to get all keys

### ISSUE THREAD

**Issue by segfaultdoc** [nats-io/nats.rs#642]
## Problem
Calls to get all keys blocks even when there is a non-zero number of keys in the store. Note that this call always blocks when there are 0 keys in the store; not sure if the latter is desired behavior or not, however the former is def not desired.

The issue seems to be correlated with items being expired from the store or perhaps just generally the number of items decreasing.

So I'm pretty sure this is an issue with the server because the behavior is only reproducible on versions > 2.8.2.

Here's some code to reproduce: https://github.com/segfaultdoc/nats_blocking

## Setup
Spin up v2.9.0 and run the above script. You'll notice logs stop getting printed after some time. I was not able to reproduce on versions 2.7.3 >= && <= 2.8.2

## Running the script
```
export RUST_LOG=info
cargo run -- --nats-url nats://127.0.0.1:4222 --bucket-config-path ../bucket.yaml
```

**Comment by Jarema** [comment]
https://github.com/nats-io/nats.rs/pull/641

**Comment by buffalu** [comment]
nice thanks!
