### ISSUE TITLE
CI should detect and fail when dependencies have incompatible licenses

### ISSUE THREAD

**Issue by code-ape** [nats-io/nats.rs#698]
### Use Case:

This will prevent accidental additions of incompatible licenses.

### Proposed Change:

- [ ] Update CI such that it fails if dependencies have a license that is not compatible with: MIT, Apache-2.0, ISC, BSD-3-Clause, OpenSSL, Unicode-DFS-2016
- [ ] Make temporary exceptions for any licenses that fail. Escalate these to @caspervonb who will own getting resolution on them and can make follow up issues if needed.

### Who Benefits From The Change(s)?

Contributors and maintainers of this repo.

### Additional Details

1. Created this in collaboration with @corbinu and @caspervonb.
2. The dependency of Ring, which has a dependency chain of BoringSSL and thus OpenSSL, is a known cause of some frustration with licensing dependency checks. References:
    1. https://github.com/briansmith/ring/blob/main/LICENSE
    2. https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

### Work Expectations

1. Goal to have this merged by end of Monday, Nov 7, 2022. Expecting @corbinu to do work.

**Comment by Jarema** [comment]
Closing, as it was implemented in #703
