### ISSUE TITLE
CI should do a spellcheck and fail if any issues are detected

### ISSUE THREAD

**Issue by code-ape** [nats-io/nats.rs#699]
### Use Case:

This will prevent misspellings which are hard to always catch as part of PR process.

### Proposed Change:

- [ ] Update CI such that it fails if cargo spellcheck detect any spelling issues.
- [ ] Add an "override" file for non-standard words which should be allowed.
- [ ] Fix any remaining spelling issues. If fixes break client library API then create a new alias and mark the misspelled one as deprecated.
- [ ] Ensure that spellcheck is always run using "US English" dictionary.

### Who Benefits From The Change(s)?

Contributors and maintainers of this repo.

### Additional Details

1. Created this in collaboration with @corbinu and @caspervonb.
2. Tool to be used: https://github.com/drahnr/cargo-spellcheck

### Work Expectations

1. Goal to have this merged noon PT on Tuesday, Nov 8, 2022. Expecting @corbinu to do work.

**Comment by caspervonb** [comment]
We did it again https://github.com/nats-io/nats.rs/issues/711

**Comment by Jarema** [comment]
implemented in #736
