### ISSUE TITLE
Reconnect logic implementation

### ISSUE THREAD

**Issue by nazar-pc** [nats-io/nats.rs#7]
There is an item in TODO about this and I think it is one of the most important ones in terms of library usability.
So I decided to create a tracking issue so that people can subscribe to and get notified when it is implemented.

What is the priority on it BTW?

**Comment by derekcollison** [comment]
Its a high priority along with TLS and Nkeys and JWT authorization.

**Comment by spacejam** [comment]
This has been implemented in #16 and I'll close this issue when version 0.3.0 is released which includes this change!

**Comment by nazar-pc** [comment]
I was following that PR, nice work :tada:

**Comment by spacejam** [comment]
This has been published in the 0.3 crate!
