### ISSUE TITLE
BUG: 'last seen' println spams

### ISSUE THREAD

**Issue by sebadob** [nats-io/nats.rs#712]
This is most probably just a very tiny thing, but with async_nats v0.22.0 and an active Jetstream connection, I get these message spams, I guess from println:

```
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
```

They always have the same sequence:
1 `not ok` message followed by 3 `ok. wait` messages (possible room for less checks / more optimization?)

**Comment by Jarema** [comment]
Yes, that's a println that should be `trace` log, will fix it. Though it's little weird behaviour.

This is related to Ordered Push Consumer and idle hearbeats.

I assume you have active Ordered Consumer.
Can you share it's config?

**Comment by sebadob** [comment]
My consumer config looks like this:

```rust
let cfg = consumer::pull::Config {
            ack_wait: Duration::from_secs(5),
            deliver_policy: DeliverPolicy::All,
            filter_subject: "register.>".to_string(),
            inactive_threshold: CONSUMER_INACTIVE_THRESHOLD,
            ..Default::default()
        };
```

**Comment by Jarema** [comment]
Ah, so it's a `watch_all`. Thanks! Will make reproducing that much easier.

**Comment by c0d3x42** [comment]
Pretty sure i'm seeing a similar behaviour in my app, I've created a small reproducible case here

https://github.com/c0d3x42/nats-object-store-not-ok 

which produces the following to stdout

```
Hello, world!
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen not ok
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen ok. wait
last seen ok. wait
last seen ok. wait
last seen not ok
last seen not ok

```

**Comment by c0d3x42** [comment]
after a bit more digging around, i suspect this issue is related to the `loop{}` block here:

https://github.com/nats-io/nats.rs/blob/main/async-nats/src/jetstream/consumer/push.rs#L399..L443

There seems to be only one place the loop can exit 
https://github.com/nats-io/nats.rs/blob/main/async-nats/src/jetstream/consumer/push.rs#L438

And FWICT the branch is never taken.

in my local testing, i have something akin to
```rust
let bucket = jetstream.get_object_store("store").await.unwrap();
tokio::spawn(async move {
 loop {
  tokio::time::sleep(tokio::time::Duration::from_secs(13)).await;
  match bucket.get("f").await {
    Ok(mut obj) => {
    ...
```

which ends up repeatedly calling https://github.com/nats-io/nats.rs/blob/main/async-nats/src/jetstream/consumer/push.rs#L379 
```rust
impl Consumer<OrderedConfig> {
    pub async fn messages<'a>(self) -> Result<Ordered<'a>, Error> {
```
and starting another never-terminating `loop{}`

Hope this helps at least a little in narrowing it down.

**Comment by Jarema** [comment]
ok, thanks. 
I was unable to replicate it.
Now it hopefully will be easier.

**Comment by sebadob** [comment]
I am sorry, I totally forgot about this issue.  
I use v0.29 by now and the issue has gone away and it is fixed (at least for me).

So from my side, we could close this issue.
