### ISSUE TITLE
Friendlier API for HeaderValue

### ISSUE THREAD

**Issue by cortopy** [nats-io/nats.rs#760]
#### Use Case:

I'm migrating from `nats` to `nats-async` and I'm bumping into convoluted ways to use messages' headers.

While in `nats` I can do:

```rust
let value: &String = message
            .headers
            .as_ref()
            .and_then(|h| h.get("my-header"));
```

In `nats-async` HeaderValue does not convert into anything, so I have to do:

```rust
let value: String = message
            .headers
            .as_ref()
            .and_then(|h| h.get("my-header"))
            .map(|header_value| header_value.iter().cloned().collect::<String>());
```

This is largely unintuitive and even forces some extra cloning

#### Proposed Change:

implement `Display` for `HeaderValue` or some way to get as a string reference

#### Who Benefits From The Change(s)?

users reading headers

#### Alternative Approaches

As above

**Comment by Jarema** [comment]
@cortopy thanks for filling the issue.

Yes, I agree that headers API needs more convinience for basic use cases.
We will add those.
