### ISSUE TITLE
Experimental async functionality not usable by other crates

### ISSUE THREAD

**Issue by ccbrown** [nats-io/nats.rs#77]
According to the changelog:

> An experimental async `Connection` is now available to adventurous explorers by calling `Options::connect_async`.

Unfortunately, the `asynk::Connection` returned by `connect_async` is not usable because `asynk` is not public.

Should `asynk` be made public?

**Comment by stjepang** [comment]
Yes, this module will be made public soon. We chose to roll out the synchronous API first and then enable the async API when we made sure the big refactor has gone smoothly.

**Comment by stjepang** [comment]
An async client is now available in the latest version of the `nats` crate - it's in the module named `asynk`.
