### ISSUE TITLE
lost messages while using `async-nats`

### ISSUE THREAD

**Issue by winary** [nats-io/nats.rs#773]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

I found `async-nats` will lost messages,  in `publish` or `subscribe`, but this not happen in `nats = "0.23.0"`
- in `publish`,  all subscriber recvive the same amount of message, but not equal to the amount of sending out
- in `subscribe`,  not all subscriber can receive all the messages

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
async-nats = "0.23.0"
#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.65.0
#### OS/Container environment:
mac/linux
#### Steps or code to reproduce the issue:
```
// pub const NATS_URL: &str = "nats://127.0.0.1:4222";
pub const NATS_URL: &str = "nats://192.168.1.247:4222";

async fn pub_sub_async() -> Result<(), async_nats::Error> {
    // subscriber
    for i in 0..5 {
        tokio::task::spawn({
            let client = async_nats::connect(NATS_URL).await?;
            let sub_id = i;
            async move {
                let mut subscriber = client.subscribe("foo.*".to_string()).await?;
                let mut count: u64 = 0;
                log::info!("{:02}] begin to subscribe", sub_id);

                while let Some(message) = subscriber.next().await {
                    if message.subject == "foo.close".to_string() {
                        break;
                    }
                    count += 1;
                }
                log::info!("{:02}] count {}", sub_id, count);
                Ok::<(), async_nats::Error>(())
            }
        });
    }

    tokio::time::sleep(tokio::time::Duration::from_secs(5)).await;
    log::info!("done sleep");

    // spawn a task publishing to foo
    for i in 0..10 {
        tokio::task::spawn({
            let client = async_nats::connect(NATS_URL).await?;
            let pub_id = i;
            async move {
                for i in 1..=5000 {
                    let subj = format!("foo.{i}");
                    let data = format!("data-{i}-{pub_id}");
                    client.publish(subj.into(), data.into()).await?;
                }
                log::info!("publish[{:02}] done", pub_id);
                Ok::<(), async_nats::Error>(())
            }
        });
    }

    tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;
    log::info!("done sleep");

    let client = nats::connect(NATS_URL)?;
    client.publish("foo.close", "foo.close_data")?;

    std::future::pending::<()>().await;

    Ok(())
}
```
#### Actual result:
```
00] begin to subscribe
01] begin to subscribe
02] begin to subscribe
03] begin to subscribe
04] begin to subscribe
done sleep
publish[00] done
publish[01] done
publish[02] done
publish[03] done
publish[04] done
publish[05] done
publish[06] done
publish[07] done
publish[08] done
publish[09] done
done sleep
00] count 37864
01] count 37864
02] count 37864
03] count 37864
04] count 37864
```

```
00] begin to subscribe
01] begin to subscribe
02] begin to subscribe
03] begin to subscribe
04] begin to subscribe
done sleep
publish[00] done
publish[01] done
publish[02] done
publish[03] done
publish[04] done
publish[05] done
publish[06] done
publish[07] done
publish[08] done
publish[09] done
done sleep
03] count 49977
01] count 49642
02] count 50000
04] count 50000
00] count 49994
```

**Comment by Jarema** [comment]
hey @winary 

That's because of different `flush` settings in old and new client.
New client is optimized for high throughput and will have a new flush mechanism introduced soon - one that will not reduce performance but will get rid most of those cases.
Thoguh, every NATS client can suffer from this.
The reason being, messages are buffered before they are sent.

Though on my machine your code works as expected, enviroments differs and to be sure, please add `client.flush.await()` at the end of each publish:

```diff
    // spawn a task publishing to foo
    for i in 0..10 {
        tokio::task::spawn({
            let client = async_nats::connect(NATS_URL).await?;
            let pub_id = i;
            async move {
                for i in 1..=5000 {
                    let subj = format!("foo.{i}");
                    let data = format!("data-{i}-{pub_id}");
                    client.publish(subj.into(), data.into()).await?;
                }
                log::info!("publish[{:02}] done", pub_id);
               + client.flush().await?;
                Ok::<(), async_nats::Error>(())
            }
        });
    }

```

**Comment by winary** [comment]
figure out ! thank you !

run `flush` after every `publish` works good !  

and  increase `subscription_capacity` can make sure message won't be miss

**Comment by HeCorr** [comment]
@Jarema sorry for bumping this but I just faced this issue of messages not being published on a short-lived CLI app and I really think this behavior should be better documented, i.e. by adding a `flush()` call to the [example code](https://docs.rs/async-nats/latest/async_nats/#publish) so people don't get caught by surprise like me and Winary did.

**Comment by Jarema** [comment]
Hey. Yes. That is a good idea. 
Are you interested in contributing?:)

**Comment by HeCorr** [comment]
> Are you interested in contributing? :)

I wouldn't mind. Is the docs page just a markdown file from the repo?
I'm new to Rust so I don't know how the docs work yet.
