### ISSUE TITLE
doc improvment on Options::max_reconnects() function

### ISSUE THREAD

**Issue by xoac** [nats-io/nats.rs#80]
Just suggestion for a small improvement in documentation:
Here:
https://docs.rs/nats/0.7.0/nats/struct.Options.html#method.max_reconnects

> Set the maximum number of reconnect attempts. If no servers remain that are under this threshold, all servers will still be attempted.

There is no information what None mean. Infinite reconnect attempts or don't attempts at all (`Some(0)`)?

**Comment by stjepang** [comment]
`None` would mean there is no limit to the number of reconnects (i.e. max_reconnects is set to infinity).

@spacejam Is it even worth making the argument an `Option<usize>` here? The Go client simply has `int` and if you don't touch the `max_reconnects` option, it defaults to infinity:

https://godoc.org/github.com/nats-io/go-nats#MaxReconnects

**Comment by spacejam** [comment]
addressed in #108
