### ISSUE TITLE
Async nats trying cluster connect

### ISSUE THREAD

**Issue by andreyddk** [nats-io/nats.rs#801]
Hi! I trying connect to cluster and got the message 
`NATS server URL is invalid: invalid port number`

env:
`NATS_CLUSTER=nats://localhost:4222,nats://localhost:14222,nats://localhost:24222
`

```
let config = config_rs::Config::new();
let nats = match async_nats::connect(config.nats.get_cluster() // String).await {
    Ok(r) => r,
    Err(e) => panic!("{}", e),
  };
```

Why its happening?

**Comment by Jarema** [comment]
Hey!

`ToServerAddrs` trait is pretty type-safe and does not try to split `&str` if that's whats passed.

You can either iterate over some collection and parse addresses, or pass slice directly.


```rust
    async fn addrs() -> Result<(), async_nats::Error> {
        let servers = vec!["demo.nats.io", "other.nats.io"];
        let client = async_nats::connect(
            servers
                .iter()
                .map(|url| url.parse())
                .collect::<Result<Vec<ServerAddr>, _>>()?
                .as_slice(),
        )
        .await?;
        
```
or
```rust
        let client = async_nats::connect(
            [
                "demo.nats.io".parse::<ServerAddr>()?,
                "other.nats.io".parse::<ServerAddr>()?,
            ]
            .as_slice(),
        )
        .await
        .unwrap();

        Ok(())
    }
```

**Comment by Jarema** [comment]
Added utility to pass `Vec` directly and some examples to the docs:
https://github.com/nats-io/nats.rs/pull/802

**Comment by andreyddk** [comment]
> Hey!
> 
> `ToServerAddrs` trait is pretty type-safe and does not try to split `&str` if that's whats passed.
> 
> You can either iterate over some collection and parse addresses, or pass slice directly.
> 
> ```rust
>     async fn addrs() -> Result<(), async_nats::Error> {
>         let servers = vec!["demo.nats.io", "other.nats.io"];
>         let client = async_nats::connect(
>             servers
>                 .iter()
>                 .map(|url| url.parse())
>                 .collect::<Result<Vec<ServerAddr>, _>>()?
>                 .as_slice(),
>         )
>         .await?;
>         
> ```
> 
> or pass list directly:
> 
> ```rust
>         let client = async_nats::connect(
>             [
>                 "demo.nats.io".parse::<ServerAddr>()?,
>                 "other.nats.io".parse::<ServerAddr>()?,
>             ]
>             .as_slice(),
>         )
>         .await
>         .unwrap();
> 
>         Ok(())
>     }
> ```

Oh its work, thank you 🙂

**Comment by Jarema** [comment]
Great!
Closing.
