### ISSUE TITLE
Reconnect loop until timeout under authorization failure

### ISSUE THREAD

**Issue by abalmos** [nats-io/nats.rs#815]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
async_nats = 0.26.0

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
1.66.1

#### OS/Container environment:
Linux Fedora 37

#### Steps or code to reproduce the issue:
Use only 

```rust
let client = async_nats::connect("<ip>").await?
```

to connect to a server with no `no_auth_user` configured.

#### Expected result:

Connect once and then return an `Err` for authorization failure.

#### Actual result:

Client tries to reconnect in a tight loop (1000s of times) until the connect attempt fails based on a timeout.

**Comment by Jarema** [comment]
Thanks for the report.
Will fix this next week.

**Comment by Jarema** [comment]
Fixed. Closinng.
