### ISSUE TITLE
subscription close does not end the subscription iterator in v0.6 and v0.7

### ISSUE THREAD

**Issue by sidred** [nats-io/nats.rs#82]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ x] Included below version and environment information
 - [ x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### natsio version (`grep 'name = "natsio"' Cargo.lock -A 1`)
version 0.7

#### rustc version (`rustc --version` - we support Rust 1.37 and up)
1.45

#### OS/Container environment:
linux (fedora 31)
#### Steps or code to reproduce the issue:
```
use std::{thread, time::Duration};

fn read_loop(subscription: nats::Subscription) {
    println!("reading messages");
    for msg in subscription.messages() {
        println!("{:?}", msg);
    }
    println!("subscription closed");
}

fn main() {
    let nats_conn = nats::connect("127.0.0.1").unwrap();

    let mut subscription = nats_conn.subscribe("some-channel").unwrap();

    let s1 = subscription.clone();
    let thread_wait = thread::Builder::new().spawn(move || read_loop(s1)).unwrap();

    thread::sleep(Duration::from_millis(2000));
    println!("stopping subscription");
    subscription.drain().unwrap();

    println!("waiting for thread");
    thread_wait.join().unwrap();
    println!("done waiting");
}
```
#### Expected result:
Expected the program to shutdown within a few seconds.

#### Actual result:
Program hangs at subscription.drain() line. Can reproduce it in v0.6 and v0.7. Works in v0.5.

replacing subscription.drain() with subscription.close() also has the same issue.

**Comment by stjepang** [comment]
Thank you for the bug report! I was able to reproduce and submitted a PR fixing it: #83

**Comment by sidred** [comment]
This is fixed for subscription.drain() but subscription.close() still has the issue, where the iterator is blocked.
