### ISSUE TITLE
Empty Header on publish

### ISSUE THREAD

**Issue by pramodsri** [nats-io/nats.rs#832]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x ] Included below version and environment information
 - [ x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
[nats/v0.23.1](https://github.com/nats-io/nats.rs/tree/nats/v0.23.1)

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.64.0 (a55dd71d5 2022-09-19)

#### OS/Container environment:
Linux ip-10-193-21-81 5.15.0-1028-aws #32~20.04.1-Ubuntu SMP Mon Jan 9 18:02:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

#### Steps or code to reproduce the issue:
1) Call publish_with_options from rust app using nats client [nats/v0.23.1]

```rust
            let pub_opts = PublishOptions {
                timeout: Some(timeout),
                ..Default::default()
            };
```
```
    js.publish_with_options(&subject, &data, &pub_opts) //subject and data can be any value.
```

2) Monitor the log published on the nats-server side (enable debug)

```
[30507] 2023/02/07 06:58:40.218293 [TRC] 172.28.1.64:57566 - cid:34 - "v0.23.1:rust:rust_stress" - <<- [SUB _INBOX.PqL9RNp6jmmnwxrMP4SQnb 1]
[30507] 2023/02/07 06:58:40.218472 [TRC] 172.28.1.64:57566 - cid:34 - "v0.23.1:rust:rust_stress" - <<- [HPUB foo.bar _INBOX.PqL9RNp6jmmnwxrMP4SQnb 12 57]
[30507] 2023/02/07 06:58:40.218531 [TRC] 172.28.1.64:57566 - cid:34 - "v0.23.1:rust:rust_stress" - <<- MSG_PAYLOAD: ["NATS/1.0\r\n\r\nR\x1d\x12\x1b\r\x00\x00\x80?\x15\x00\x00\x00@\x1d\x00\x00@@%\x00\x00\x80@-\x00\x00\xa0@0\x06b\f\b\x9f퇟\x06\x10\xb5֚\xb9\x01"]
[30507] 2023/02/07 06:58:40.219248 [TRC] 172.28.1.64:57566 - cid:34 - "v0.23.1:rust:rust_stress" - ->> [MSG _INBOX.PqL9RNp6jmmnwxrMP4SQnb 1  50]
```

Note the `MSG_PAYLOAD ["NATS/1.0\r\n\r\nR\x1d\x12\x1b\r\x00\x00\x80?\x15\x00\x00\x00@\x1d\x00\x00@@%\x00\x00\x80@-\x00\x00\xa0@0\x06b\f\b\x9f퇟\x06\x10\xb5֚\xb9\x01"]`

`"NATS/1.0\r\n\r\nR"` is 12 bytes and is empty.  It is likely a bug in the [rust nats client library](https://github.com/nats-io/nats.rs/blob/0a7dffbb360d084fdbf717b87ec8a766d4a2aaf2/nats/src/jetstream/mod.rs#L612), if we publish with options, we end up with an empty header?

This tripped the java client library and got fixed recently - https://github.com/nats-io/nats.java/pull/839

#### Expected result:

- publish message with no empty header.

#### Actual result:

- publish message with empty heaade.

**Comment by wallyqs** [comment]
I think this fixed it? https://github.com/nats-io/nats.rs/pull/831

**Comment by pramodsri** [comment]
Looks like it, please close if it's already fixed..

**Comment by scottf** [comment]
@pramodsri Just being clear, that this empty header is technically legal, it was the java client that did not handle it properly.

**Comment by Jarema** [comment]
@pramodsri @wallyqs it was improved for async-nats client, not for legacy sync client.
If you're still using `nats` crate, I can fix it there too.

**Comment by pramodsri** [comment]
we have not moved to async-nats yet, would like to, are the APIs compatible
with nats crate?

**Comment by Jarema** [comment]
@pramodsri I made a fix in https://github.com/nats-io/nats.rs/pull/833

Will release a sync client over the weekend.

It is a new API, also async, so it is different.
Our users had success with migrating quickly, though.

I would advise waiting before starting migration, as we're just about to land last breaking changes before issuing 1.0 version.
Those are expected to land in more or less two weeks.

**Comment by pramodsri** [comment]
Thanks for the update Jarema! We will wait for the next release before we migrate to async-nats

**Comment by pramodsri** [comment]
Hello Tomasz

When do you think we can get a stable version of nats library for rust. It
will help us plan.

Regards
Pramod
