### ISSUE TITLE
Unclear error message when publishing to non-existent subject

### ISSUE THREAD

**Issue by ronaldslc** [nats-io/nats.rs#834]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
async-nats 0.27.1

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
1.67

#### OS/Container environment:
Linux

#### Steps or code to reproduce the issue:
```rust
    let msg = Publish::build()
        .message_id("some-id")
        .payload(em.into_bytes()?);

    let ack = jetstream
        .send_publish("NON-EXISTENT".to_owned(), msg).await?.await?;
```

#### Expected result:
A friendly error message

#### Actual result:
EOF while parsing a value coming from core/src/ops/function.rs:507

**Comment by Jarema** [comment]
thanks for the report.
Indeed, not very intuitive.
Fixed in  #835
