### ISSUE TITLE
Latency Compared to Go client

### ISSUE THREAD

**Issue by dennybritz** [nats-io/nats.rs#85]
I've been trying to benchmark NATS for my use case. Using the [latency-tests](https://github.com/nats-io/latency-tests) tool I get something like this:

```
./latency -tr 1000 -tt 5s -sz 512
==============================
Pub Server RTT : 98µs
Sub Server RTT : 80µs
Message Payload: 512B
Target Duration: 5s
Target Msgs/Sec: 1000
Target Band/Sec: 1000K
==============================
HDR Percentiles:
10:       88µs
50:       108µs
75:       122µs
90:       137µs
99:       202µs
99.9:     253µs
99.99:    265µs
99.999:   982µs
99.9999:  982µs
99.99999: 982µs
100:      982µs
==============================
```

However, when using the Rust client and doing a very simple benchmark, my latency is ~2-5x of that. The following code is the simplest variation I have, but I tried various things: Reading and writing in a different thread, using tokio, etc, to replicate more closely what the Go benchmark does. I also tried putting explicit flush calls. The results are always the same. Am I doing something fundamentally wrong in the benchmark?

For reference, the `rtt` function gives the latency I expect, around 80 micros.

```rust
    let nc1 = nats::connect("localhost:4222").unwrap();
    let nc2 = nats::connect("localhost:4222").unwrap();
    let sub = nc2.subscribe("foo").unwrap();
    loop {
        let now = std::time::Instant::now();
        nc1.publish("foo", "").unwrap();
        sub.next().unwrap();
        println!("RTT: {:?}", now.elapsed());
        std::thread::sleep(std::time::Duration::from_millis(100));     
    }
```

```
RTT: 339.942µs
RTT: 337.414µs
RTT: 367.48µs
RTT: 357.508µs
RTT: 333.453µs
RTT: 392.305µs
RTT: 302.826µs
RTT: 495.053µs
RTT: 213.117µs
RTT: 187.48µs
RTT: 351.434µs
RTT: 419.223µs
RTT: 437.84µs
RTT: 376.603µs
RTT: 295.522µs
RTT: 303.573µs
RTT: 361.104µs
RTT: 306.155µs
RTT: 405.807µs
RTT: 313.317µs
RTT: 403.848µs
RTT: 315.56µs
RTT: 386.924µs
RTT: 379.003µs
RTT: 378.367µs
RTT: 331.52µs
RTT: 444.34µs
RTT: 354.675µs
RTT: 346.96µs
RTT: 482.608µs
RTT: 297.046µs
RTT: 214.371µs
RTT: 373.295µs
RTT: 422.137µs
RTT: 358.374µs
RTT: 374.481µs
RTT: 371.184µs
```

**Comment by dennybritz** [comment]
Okay, I found it. If I change the sleep duration to `1ms` instead of `100ms` to be closer to the Go benchmark `msg/sec`, the latencies seem much more reasonable:

```
Latency: 121µs
Latency: 115µs
Latency: 121µs
Latency: 139µs
Latency: 123µs
Latency: 141µs
Latency: 123µs
Latency: 164µs
Latency: 132µs
Latency: 164µs
Latency: 145µs
Latency: 134µs
Latency: 129µs
Latency: 146µs
Latency: 143µs
Latency: 129µs
Latency: 151µs
Latency: 178µs
Latency: 107µs
Latency: 104µs
Latency: 159µs
Latency: 331µs
Latency: 109µs
Latency: 137µs
Latency: 110µs
Latency: 135µs
Latency: 119µs
Latency: 119µs
Latency: 127µs
Latency: 148µs
Latency: 165µs
Latency: 158µs
```

I guess this just a matter of flushing? This can be closed, but I'd still be curious to hear the exact reason :)

**Comment by spacejam** [comment]
off the bat this sounds like classic cache pollution where the working set gets cold due to giving up the core for so long

**Comment by saabye-io** [comment]
I writting a project in RUST and use NATS. During a latency test of the project I found that the RUST Nats client does have a higher latency than the GO Nats client.

To further investigate this I ported the latency-test from GO to RUST: [https://github.com/saabye-io/nats-latency-test.rs](https://github.com/saabye-io/nats-latency-test.rs)

Sometimes a message can take 41ms (machine dependent) to arrive and the only thing I can think of why, is the garbage collector for NATS.
However, the same latency test with the GO version does not show this time...

Can anyone tell me why?

**Comment by spacejam** [comment]
@saabye-io does this happen with the current master branch? It's not clear what's happening on your machine or the open internet while comparing these. If you're trying to benchmark two processes against each other, please disable things like turbo boost or run interleaved workloads to rule out transient system maintenance tasks or other competing resource usage. Turbo boost messes up almost every "side-by-side" comparison I've seen posted and invalidates results due to shifting the clock speed down for whichever workload runs second. Please run the comparison against a local nats server, not over the open internet, which is prone to many fluctuations outside of your or our control.

**Comment by saabye-io** [comment]
@spacejam I have only used a local containerized nats server and plain executable on my local host. I'm perfectly aware of not using the internet for these kind of latency tests.

I have just updated the nats crate to: nats v0.9.0 (was 0.8.6)

I did not consider the turbo boost part, however, and I can see that the current scaling_governor is schedutil (I'm on linux). 
I have set the cpu's to performance with:
```bash
$ echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
```

The go latency went faster:
```
$ ./latency -tt 1s -tr 1000 -sz 1024
==============================
Pub Server RTT : 130µs
Sub Server RTT : 103µs
Message Payload: 1.0K
Target Duration: 1s
Target Msgs/Sec: 1000
Target Band/Sec: 16Mbps
==============================
HDR Percentiles:
10:       114µs
50:       133µs
75:       143µs
90:       156µs
99:       187µs
99.9:     305µs
99.99:    315µs
99.999:   315µs
99.9999:  315µs
99.99999: 315µs
100:      315µs
==============================
Actual Msgs/Sec: 1003
Actual Band/Sec: 16Mbps
Minimum Latency: 93µs
Median Latency : 133µs
Maximum Latency: 315µs
1st Sent Wall Time : 2.061ms
Last Sent Wall Time: 996.664ms
Last Recv Wall Time: 996.664ms
```

However the RUST latency was almost the same. The fastes messages was faster than with the schedutil governor.
```
$ ./latency-rs --tt 1s --tr 1000 --sz 1024
==============================
Pub Server RTT : 114 µs
Sub Server RTT : 83 µs
Message Payload: 1.0K
Target Duration: 1s
Target Msgs/Sec: 1000
Target Band/Sec: 16Mbps
==============================
HDR Percentile
10:       423.935µs
50:       12.836863ms
75:       22.626303ms
90:       27.967487ms
99:       31.834111ms
99.9:     39.321599ms
99.99:    39.321599ms
99.999:   39.321599ms
99.9999:  39.321599ms
99.99999: 39.321599ms
100:      39.321599ms
==============================
Actual Msgs/Sec: 1001
Actual Band/Sec: 16Mbps
Minimum Latency: 71.265µs
Median Latency : 12.830794ms
Maximum Latency: 39.303587ms
1st Sent Wall Time : 1.506923774s
Last Sent Wall Time: 998.749746ms
Last Recv Wall Time: 998.750463ms
```

I you have more suggestions, please shoot.

**Comment by stjepang** [comment]
On my MacBook, Rust client v0.8.6 does have noticeably higher latencies but v0.9.1 is very similar to the Go client. `nats-server` is running locally (not inside Docker, no command line flags). I didn't fiddle with turbo boost or anything like that (it's left as is by default).

Go client:

```
$ latency-tests -tt 1s -tr 1000 -sz 1024
==============================
Pub Server RTT : 360µs
Sub Server RTT : 229µs
Message Payload: 1.0K
Target Duration: 1s
Target Msgs/Sec: 1000
Target Band/Sec: 16Mbps
==============================
HDR Percentiles:
10:       154µs
50:       225µs
75:       295µs
90:       324µs
99:       400µs
99.9:     498µs
99.99:    533µs
99.999:   533µs
99.9999:  533µs
99.99999: 533µs
100:      533µs
==============================
Actual Msgs/Sec: 999
Actual Band/Sec: 16Mbps
Minimum Latency: 72µs
Median Latency : 225µs
Maximum Latency: 533µs
1st Sent Wall Time : 4.051ms
Last Sent Wall Time: 1.000893s
Last Recv Wall Time: 1.000894s
```

Rust client v0.8.6:

```
$ c r --release -- --tt 1s --tr 1000 --sz 1024
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/latency-rs --tt 1s --tr 1000 --sz 1024`
==============================
Pub Server RTT : 572 µs
Sub Server RTT : 820 µs
Message Payload: 1.0K
Target Duration: 1s
Target Msgs/Sec: 1000
Target Band/Sec: 16Mbps
==============================
HDR Percentile
10:       383.231µs
50:       767.487µs
75:       1.198079ms
90:       1.503231ms
99:       1.762303ms
99.9:     1.989631ms
99.99:    1.989631ms
99.999:   1.989631ms
99.9999:  1.989631ms
99.99999: 1.989631ms
100:      1.989631ms
==============================
Actual Msgs/Sec: 1008
Actual Band/Sec: 16Mbps
Minimum Latency: 181µs
Median Latency : 767.5µs
Maximum Latency: 1.989ms
1st Sent Wall Time : 1.619191s
Last Sent Wall Time: 991.645ms
Last Recv Wall Time: 991.669ms
```

Rust client v0.9.1:

```
$ c r --release -- --tt 1s --tr 1000 --sz 1024
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/latency-rs --tt 1s --tr 1000 --sz 1024`
==============================
Pub Server RTT : 505 µs
Sub Server RTT : 700 µs
Message Payload: 1.0K
Target Duration: 1s
Target Msgs/Sec: 1000
Target Band/Sec: 16Mbps
==============================
HDR Percentile
10:       192.127µs
50:       258.047µs
75:       300.031µs
90:       340.223µs
99:       452.095µs
99.9:     865.279µs
99.99:    865.279µs
99.999:   865.279µs
99.9999:  865.279µs
99.99999: 865.279µs
100:      865.279µs
==============================
Actual Msgs/Sec: 1002
Actual Band/Sec: 16Mbps
Minimum Latency: 130µs
Median Latency : 258µs
Maximum Latency: 865µs
1st Sent Wall Time : 1.541532s
Last Sent Wall Time: 997.714ms
Last Recv Wall Time: 997.716ms
```

**Comment by saabye-io** [comment]
Did a bit more digging and found that nats-server delays a TCP ACK and the client is then buffering up the messages. 
I ran the rust latency test with the lib updated to 0.9.2 and used NATS 2.1.9 in a container.
```
latency-rs --tr 100 --tt 1s --sz 1024
```

Got the percentiles:
```
HDR Percentile
10:       222.079µs
50:       14.213119ms
75:       25.346047ms
90:       32.882687ms
99:       40.075263ms
99.9:     40.534015ms
99.99:    40.534015ms
99.999:   40.534015ms
99.9999:  40.534015ms
99.99999: 40.534015ms
100:      40.534015ms
```

I've captured the packages i wireshark and this is was I found for two normal/fast flow: Sender sends to NATS, NATS respond with ACK, NATS sends to Receiver, Receiver respond with ACK:
![image](https://user-images.githubusercontent.com/76842106/107222642-78e40900-6a15-11eb-9055-f1df31fe43ef.png)

Hint: source port 54850 is the sending client and destination port 54860 is the receiving client:

Then after message 15 (packet no. 100) this happens: Sender sends to NATS, NATs sends to Receiver, Receiver respond with ACK, **PAUSE FOR 40ms**, NATS respond with ACK to Sender. 
![image](https://user-images.githubusercontent.com/76842106/107235568-16930480-6a25-11eb-87d2-e5171cab1ff7.png)

And this is now the new normal reaction for the test...

### Comparing with the GO latency test, 

Run with:
```
./latency -tr 100 -tt 1s -sz 1024
```

Got the percentile:
```
HDR Percentiles:
10:       196µs
50:       211µs
75:       223µs
90:       233µs
99:       265µs
99.9:     296µs
99.99:    296µs
99.999:   296µs
99.9999:  296µs
99.99999: 296µs
100:      296µs
```

The normal/fast flow was seen obviously. 

At some point a funny thing starts to happend, as the Receiving part was not ACK'ing back:
![image](https://user-images.githubusercontent.com/76842106/107241349-33323b00-6a2b-11eb-94be-dcaaffd3e18c.png)

And then the (almost) same thing happends as with the rust-latency: Sender sends to NATS, NATS sends to Receiver, Receiver respond with ACK.... **NATS never respond ACK to Sender**
![image](https://user-images.githubusercontent.com/76842106/107247660-cc645000-6a31-11eb-8a5e-e80026c38378.png)

### Round up
It seems that the rust-client waits for a package to be acknowledge before sending the next package, where the GO client just keep sending anyway. 

Why do I even see this when others dont.... I'm considering setting up a public NATS if anybody wants to help.

**Comment by spacejam** [comment]
@saabye-io awesome, thanks for reporting this data! I think this is perfect evidence that #141 should be accepted. I'll merge it in now and do a release. Once 0.9.3 is released, if you have time to do a follow-up, I'd be quite curious to see if it changes this break-down. I'm expecting it will improve the delayed ack behavior.

**Comment by saabye-io** [comment]
@spacejam #141 did it!

Now with the same NATS server, 2.1.9 in docker, and lib updated to 0.9.3 it look like this:
```
$ ./latency-rs --tr 100 --tt 1s --sz 1024
==============================
Pub Server RTT : 160 µs
Sub Server RTT : 112 µs
Message Payload: 1.0K
Target Duration: 1s
Target Msgs/Sec: 100
Target Band/Sec: 1.6Mbps
==============================
HDR Percentile
10:       120.127µs
50:       136.319µs
75:       151.167µs
90:       173.183µs
99:       264.447µs
99.9:     334.591µs
99.99:    334.591µs
99.999:   334.591µs
99.9999:  334.591µs
99.99999: 334.591µs
100:      334.591µs
==============================
Actual Msgs/Sec: 98
Actual Band/Sec: 1.5Mbps
Minimum Latency: 116.439µs
Median Latency : 136.571µs
Maximum Latency: 334.478µs
1st Sent Wall Time : 893.560965ms
Last Sent Wall Time: 1.011699727s
Last Recv Wall Time: 1.011700839s
```

And with some bigger numbers, just be sure:

```
$ ./latency-rs --tr 10000 --tt 1s --sz 16184
==============================
Pub Server RTT : 127 µs
Sub Server RTT : 136 µs
Message Payload: 16K
Target Duration: 1s
Target Msgs/Sec: 10000
Target Band/Sec: 2.4Gbps
==============================
HDR Percentile
10:       108.095µs
50:       198.399µs
75:       254.847µs
90:       307.711µs
99:       534.015µs
99.9:     756.735µs
99.99:    858.111µs
99.999:   942.079µs
99.9999:  942.079µs
99.99999: 942.079µs
100:      942.079µs
==============================
Actual Msgs/Sec: 9981
Actual Band/Sec: 2.4Gbps
Minimum Latency: 81.012µs
Median Latency : 198.377µs
Maximum Latency: 941.766µs
1st Sent Wall Time : 1.24520117s
Last Sent Wall Time: 1.001848448s
Last Recv Wall Time: 1.001849199s
```

It look good! Thanks!

**Comment by spacejam** [comment]
thanks for the high quality analysis making it clear that @andy-k's PR would be a big win :)

**Comment by stjepang** [comment]
This seems to be resolved so I’m closing the issue.
