### ISSUE TITLE
Replace demo.nats.io with localhost?

### ISSUE THREAD

**Issue by stjepang** [nats-io/nats.rs#87]
In unit tests, we're using demo.nats.io, which is good for demo purposes, but I'm not sure about CI. The demo server has been flaky a couple of times before. How would you feel about perhaps using a NATS server running on localhost instead?

**Comment by derekcollison** [comment]
You could, demo is not flaky per se but how far away you are is.. ;)

Also we will be investing in demo and allowing sandboxed behavior that could be applicable to CI. Your call.

**Comment by stjepang** [comment]
It appears this was an issue with my local network, not demo.nats.io. Closing.
