### ISSUE TITLE
kv::Store::watch with DeliverPolicy::LastPerSubject

### ISSUE THREAD

**Issue by itytophile** [nats-io/nats.rs#879]
#### Use Case:
I want to subscribe to some keys and want their "initial" values in the same stream. The nats cli and nats.c have this behavior by default.
#### Proposed Change:
A `watch` method that can use `DeliverPolicy::LastPerSubject`.
#### Who Benefits From The Change(s)?
Devs who don't want to fetch the initial values before watching the keys with multiple operations.

**Comment by Jarema** [comment]
Thanks for filling out the issue!

I don't think this should be the default behaviour, but it will be added as an option.

**Comment by itytophile** [comment]
Thanks a lot! I'll close the issue.
