### ISSUE TITLE
async-nats 0.28 no field `bytes` on type `BatchConfig`

### ISSUE THREAD

**Issue by ronaldslc** [nats-io/nats.rs#883]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included below version and environment information
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
async-nats 0.28

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
1.67.1

#### OS/Container environment:
Linux

#### Steps or code to reproduce the issue:
jetstream::consumer:pull.rs line 577
|| (self.batch_config.bytes > 0

bytes does not exist

**Comment by ronaldslc** [comment]
this is in 0.28 tagged release, believe this may already be fixed in latest release, please release and update as it's become unbuildable.

Some strange thing has happened as I was compiling with 0.28 for a while, and it did not through the compilation error until today after I did a `cargo update`

**Comment by Jarema** [comment]
This is weird. All releases and even merges into main has to pass CI, which builds and tests.

Can you show me exact git commit hash you saw this on?

**Comment by ronaldslc** [comment]
not sure what happened, but I cleared my cache and have cargo redownload the package and it was fine
