### ISSUE TITLE
`subscribe` returns private `SubscribeError`

### ISSUE THREAD

**Issue by skreborn** [nats-io/nats.rs#897]
With the introduction of the concrete error types in `0.29.0`, [`async_nats::client::Client::subscribe`](https://github.com/nats-io/nats.rs/blob/2ad3c984a56a2f8f97f9901ba2aab2f5dd35f7c2/async-nats/src/client.rs#L389-L403) now returns [`async_nats::client::SubscribeError`](https://github.com/nats-io/nats.rs/blob/2ad3c984a56a2f8f97f9901ba2aab2f5dd35f7c2/async-nats/src/client.rs#L579), but this type is not exposed outside of the crate.

A workaround for now is to map it manually to [`async_nats::RequestError`](https://github.com/nats-io/nats.rs/blob/2ad3c984a56a2f8f97f9901ba2aab2f5dd35f7c2/async-nats/src/client.rs#L601-L604).

```rust
let mut subscriber = self.client.subscribe(SUBJECT).await.map_err(async_nats::RequestError::from)?;
```

**Comment by Jarema** [comment]
Will issue fix and patch today.

Thanks for the report!
