### ISSUE TITLE
Reduce the use of `#[serde(default)]`

### ISSUE THREAD

**Issue by paolobarbolini** [nats-io/nats.rs#898]
There are a few structs with `#[serde(default)]` placed on every field. This is kind of scary. It's like some S3 clients that have every field as nullable because who knows what the server could answer with. It'd be nice to remove some of the them in order to have a guarantee about which fields are supposed to always be present and which really may not.

**Comment by n1ghtmare** [comment]
Yeah, sure! I'm on it.
