### ISSUE TITLE
Request is blocking

### ISSUE THREAD

**Issue by crackcomm** [nats-io/nats.rs#90]
Hey, I'm trying to use your client but imagine my great disappointment after seeing:

```Rust
pub fn request(&self, subject: &str, msg: impl AsRef<[u8]>) -> io::Result<Message> {
    future::block_on(self.0.request(subject, msg)).map(Message::from_async)
}
```

Could you add ` pub` modifier to `mod asynk`?

**Comment by andrewbanchich** [comment]
I'm also waiting for this to get async. Until then, I've been using [rants](https://github.com/davidMcneil/rants), but I'd far prefer to use he official client.

**Comment by crackcomm** [comment]
@andrewbanchich thank I will take a look at this client.

**Comment by wayofthepie** [comment]
@crackcomm the async methods are exposed through here https://github.com/nats-io/nats.rs/blob/master/src/options.rs#L248. I think the reason they are hidden from the docs is that the API is not considered stable yet.

**Comment by spacejam** [comment]
Hey folks, we are aiming to cut a release that publicizes the asynk module tomorrow. Because it is pretty new, there may be a little more risk when using it, so please let us know right away if you hit any issues.

**Comment by stjepang** [comment]
A new version with the `asynk` module exposed has been published: https://docs.rs/nats/0.7.3/nats/asynk/index.html

**Comment by crackcomm** [comment]
Thank you all!
