### ISSUE TITLE
JetStream examples may be out of sync

### ISSUE THREAD

**Issue by margorczynski** [nats-io/nats.rs#906]
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included below version and environment information
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
nats --version: 0.35
async-nats = "0.29.0"

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.68.0 (2c8cc3432 2023-03-06)

#### OS/Container environment:
MacOS 12.6.3

#### Steps or code to reproduce the issue:
```rust
#[tokio::main]
async fn main() -> Result<(), async_nats::Error> {
    setup();

    let client = async_nats::connect("nats://localhost:4222").await?;

    let jetstream = async_nats::jetstream::new(client.clone());

    jetstream.create_stream(jetstream::stream::Config {
        name: "SOME_STREAM".to_string(),
        subjects: vec!["subject".to_string()],
        ..Default::default()
    }).await?;

    for i in 0..500 {
        info!("Publishing {}", i);
        jetstream
            .publish("subject".to_string(), format!("hello {i}").into())
            .await?;
    }

    client.flush();

    Ok(())
}
```

The setup() is simply:

```rust
static INIT: Once = Once::new();

pub fn setup() {
    INIT.call_once(|| {
        SimpleLogger::new()
            .with_level(LevelFilter::Info)
            .init()
            .unwrap();
    });
}
```

#### Expected result:
500 messages in stream

#### Actual result:
Random number of messages delivered (e.g. 390, 470) instead of 500. No error thrown by client.
The server trace logs look like it never got the publish request - so my assumption is there is some issue with the async nats library.

The client.flush() I've added later but it didn't help with the issue.

**Comment by Jarema** [comment]
@margorczynski In your example, you do not await acks before closing the client, nor you `await` `client.flush()`.
That's the reason of behaviour you see.

**Comment by margorczynski** [comment]
It looks like its my bad, just started using Rust recently and looks like I missed the await as @Jarema mentioned - just assumed that the (Ok) await on the publish should be effectively evidence that it got delivered successfully.
Closing and thank you for the help.

**Comment by margorczynski** [comment]
One thing to mention - is there a reason the .flush.await is missing from e.g. https://github.com/nats-io/nats.rs/blob/main/async-nats/examples/concurrent.rs ?

**Comment by n1ghtmare** [comment]
Yeah @caspervonb, I'll take it!

**Comment by Jarema** [comment]
Before closing this after #911 was merged, let's ensure all examples are updated, not only the concurrent one.

**Comment by Jarema** [comment]
As all examples are fine, closing.

Thanks @margorczynski for reporting on that!
