### ISSUE TITLE
Add JetStream usage example

### ISSUE THREAD

**Issue by andrewbanchich** [nats-io/nats.rs#95]
It would be helpful for those of us using JetStream to have an example of how to use the existing NATS client for streaming messages.

**Comment by derekcollison** [comment]
Agree, as we settle on last feature set we are looking at the client lib additions for basic pub and sub. Management will be a separate package based on the client language impl/ecosystem.

We plan to have more discussions to nail this down in the next week or two.

**Comment by andrewbanchich** [comment]
The thing I'm specifically struggling with is implementing the `Stream` trait to create a stream of `Message`s using a JetStream consumer.

Any suggestions on how to do this @stjepang ? I want to process `Message`s concurrently so a `Stream` would be ideal, but I can't find any way to use req / rep with `nats.rs` in that way.

**Comment by andrewbanchich** [comment]
Closing in favor of #137
