### ISSUE TITLE
Public Nats-Server mocking crate for unit-testing

### ISSUE THREAD

**Issue by Samiisd** [nats-io/nats.rs#960]
### Use case

- Unit testing Rust projects that are using nats
- Mimick nats-server behavior
- allow to run multiple independent unit tests in parallel

### Proposed change

There's already such a project here, `nats-server` crate (instantiate a real nats-server instance on an unused port. Already used for unit-testing by this nats-rs.

So the easy way around would simply be to make it a public crate that we could add as a dev-dependency.

### Who benefits from the change(s)?

User needing integration tests for their rust app/lib where nats is important

### Alternative Approaches

Implement an actual mocking server:

Pros:
- No external software dependency for the unit tests
- Not port bounded number of parallel unit tests (even tho 65k port should be more than enough)
- Lighter solution: executing the actual `nats-server` binary comes at a cost (that's probably negligible though)

Cons:
- Can most likely only handle simple scenarios, unless too much work is spent on it
- might take time to implement
- might benefit only a small amount of people

Provided the cons, I don't think it's worth it considering a full mocking solution. What is already here should be more than enough for most use cases.

**Comment by Jarema** [comment]
Hey.
We have been considering it for some time.

Mocking server behaviour is complex, but spawning the actual server - is very easy and lightweight, with the only disadvantage being the requirement for the nats-server binary.

We will publish crate for `nats-server` (under different name though) soon.

**Comment by Samiisd** [comment]
Great, thanks

**Comment by barafael** [comment]
@Samiisd can this issue be closed?

**Comment by Samiisd** [comment]
Yes, thanks @barafael
