### ISSUE TITLE
FlushError or SubscribeError is not publicly available

### ISSUE THREAD

**Issue by esemeniuc** [nats-io/nats.rs#966]
### Use case

Useful for sharing error information with any callers of `flush()`

### Proposed change

Move https://github.com/nats-io/nats.rs/blob/37654314c3d19b8791cd469c40cf80a34bf6d5d9/async-nats/src/client.rs#L662 to lib.rs or other public place.

Also https://github.com/nats-io/nats.rs/blob/37654314c3d19b8791cd469c40cf80a34bf6d5d9/async-nats/src/client.rs#L604

### Who benefits from the change(s)?

App developers, library writers

**Comment by caspervonb** [comment]
Marking as a bug as these types accidentally got voldemorted.
Propose making the module public, but re-export client at top level.
