### ISSUE TITLE
Update nkeys dependency to 0.3.0

### ISSUE THREAD

**Issue by vados-cosmonic** [nats-io/nats.rs#993]
### Use case

Hi NATS team,

While working on [wasmCloud][wasmcloud] we've been working on using a more recent versions of `nkeys` (`0.3.0`+) and we've found that `async-nats` is causing a resolution to a lower version (`0.2.0`). Of course when we looked we saw that 

Could we update the version of nkeys to use a more modern version like `0.3.0` ?

I can submit a PR (I ran a quick build and `async-nats` builds just fine locally).

[wasmcloud]: https://github.com/wasmCloud

### Proposed change

Update `nkeys` dep to `0.3.0`

### Who benefits from the change(s)?

Users wanting ot use newer nkeys functionality (ex. wasmCloud)

**Comment by Jarema** [comment]
Hey @vados-cosmonic !

Thanks for filing the issue.

Yes, of course. It should run on the newest version.
Feel free to issue the PR!

**Comment by vados-cosmonic** [comment]
Hey @Jarema thanks for taking a look! I've just put up [the PR](https://github.com/nats-io/nats.rs/pull/995)
