### ISSUE TITLE
Why doesn't jetstream::request use RequestError?

### ISSUE THREAD

**Issue by bbaldino** [nats-io/nats.rs#996]
`Client::request` uses`RequestError` for errors, which is nice for detecting cases when there are no subscribers.  `jetstream::Context::request` returns `dyn Error`, though, which means it would require something like downcasting to detect problems like `NoSubscribers`.  

I see that `Context::request` makes serde calls, so it needs to surface those errors, but it would still be nice to be able to get at the `RequestError` more conveniently...perhaps some kind of `SerdeError` could be added to `RequestErrorKind`?

**Comment by Jarema** [comment]
It's beceuse only Core NATS got recently a change with concrete error types.

JetStream will follow up soon with #874

**Comment by bbaldino** [comment]
Cool, thanks!
